
/* =========================================================
   VINCE ALVENDIA — portfolio engine
   All imagery is generated by code. Hero = 6 live scenes
   (programming / networking / hardware / data / UI / cyber).
   Projects = 6 different UI mockups (dashboard, queue,
   website, phone app, kanban, game). No photo URLs.
   ========================================================= */
const pad2 = n => String(n).padStart(2, '0');
const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const finePointer  = window.matchMedia('(pointer: fine)').matches;

function makeCanvas(w, h) { const c = document.createElement('canvas'); c.width = w; c.height = h; return c; }
const GLYPHS = '{}[]()<>=+*/;:.,#$&_?!|~^%@0123456789abcdefghijklmnopqrstuvwxyz';
const rc = () => GLYPHS[Math.random() * GLYPHS.length | 0];

function rrect(g, x, y, w, h, r) {
  g.beginPath();
  g.moveTo(x + r, y);
  g.arcTo(x + w, y, x + w, y + h, r);
  g.arcTo(x + w, y + h, x, y + h, r);
  g.arcTo(x, y + h, x, y, r);
  g.arcTo(x, y, x + w, y, r);
  g.closePath();
}
function txt(g, s, x, y, font, color, align) {
  g.font = font; g.fillStyle = color;
  if (align) g.textAlign = align;
  g.fillText(s, x, y);
  if (align) g.textAlign = 'left';
}
function drawCursorShape(g, x, y, s) {
  g.save();
  g.translate(x, y); g.scale(s, s);
  g.beginPath();
  g.moveTo(0, 0); g.lineTo(0, 17); g.lineTo(4.4, 12.2); g.lineTo(7.2, 17.8);
  g.lineTo(10.2, 16.3); g.lineTo(7.5, 10.9); g.lineTo(13, 10.4); g.closePath();
  g.fillStyle = '#f5f5f5'; g.fill();
  g.strokeStyle = 'rgba(0,0,0,.6)'; g.lineWidth = 1; g.stroke();
  g.restore();
}

/* ---------- Project data (EDIT with your real projects) ---------- */
const PROJECTS = [
  {
    title: 'INTAN ELYU', cat: 'SYSTEM — TOURISM MANAGEMENT', client: 'City Tourism Office · La Union', year: '2026',
    role: 'Full-Stack Developer & UI Architect', stack: ['Vanilla PHP', 'JavaScript', 'MySQL', 'Laravel'], ui: 'dashboard',
    shot: 'project/IntanElyu.png',
    desc: 'An official tourism management portal and administrative system for La Union (Intan Elyu). Built for the City Tourism Office and PICTO to manage tourist destinations, track visitor arrivals, maintain secure administrator authentication, and provide a digital showcase for local spots like Tangadan Falls, surfing points, and heritage landmarks.',
    metrics: [['PICTO', 'official portal'], ['100%', 'audit trail'], ['20+', 'destinations logged']]
  },
  {
    title: 'SKY MALL WEB SYSTEM', cat: 'SYSTEM — COMMERCIAL SPACE LEASING', client: 'Commercial Space Manager · Manna Mall', year: '2026',
    role: 'Lead Developer & DB Architect', stack: ['React', 'Bootstrap', 'CSS', 'Python'], ui: 'dashboard',
    shot: 'project/SkyMall.png',
    desc: 'A commercial space and lease management platform built for La Union Sky Mall (Manna Mall). Features tenant authentication, commercial unit allocation, automated lease schedule tracking, payment records, and an administrative dashboard for commercial property operations.',
    metrics: [['50+', 'commercial units'], ['0', 'manual logbooks'], ['Realtime', 'tenant portal']]
  },
  {
    title: 'AURALIS AI', cat: 'APP — CONVERSATIONAL AI & LLM WORKSPACE', client: 'Self-initiated · AI Platform', year: '2026',
    role: 'Full-Stack Developer & AI Systems Architect', stack: ['Vanilla PHP', 'Laravel', 'MySQL', 'REST API'], ui: 'auralis',
    shot: 'project/Auralis.png',
    desc: 'An intelligent conversational AI platform and multi-model workspace inspired by ChatGPT and Claude. Engineered with a modular Vanilla PHP and Laravel backend, MySQL relational conversation & message persistence, and asynchronous REST APIs supporting streaming prompt completion. Features multi-model routing (GPT-OSS 120B), prompt starters (SQL indexes, email drafting, REST vs GraphQL analysis), conversation categorization (All, Pinned, Archived), file attachments, and a refined warm minimalist interface.',
    metrics: [['Sub-100ms', 'API latency'], ['Multi-Model', 'LLM orchestration'], ['100%', 'REST API & MySQL persistence']]
  },
  {
    title: 'LOUISGRADE', cat: 'SYSTEM — STUDENT RECORDS', client: 'Course project · SLC', year: '2024',
    role: 'Solo build', stack: ['PHP', 'MySQL', 'Bootstrap', 'jQuery'], ui: 'dashboard',
    desc: 'A grading and records system built to replace spreadsheet chaos: transmuted PH grades (1.00–5.00 scale), attendance tracking, printable report cards, and role-based logins for teachers and admins. Defended it over-prepared, twice.',
    metrics: [['1.00', 'grade earned'], ['300+', 'records handled'], ['0', 'paper trails']]
  },
  {
    title: 'PUROKCONNECT', cat: 'SYSTEM — COMMUNITY', client: 'Barangay pilot project', year: '2024',
    role: 'Design, code, deploy', stack: ['PHP', 'MySQL', 'Tailwind'], ui: 'queue',
    desc: 'A barangay information and clearance-request system: residents file requests online, officials process them with a full audit trail. Built after watching my own barangay run on logbooks and patience.',
    metrics: [['5 min', 'clearance processing'], ['120', 'residents in pilot'], ['1', 'student, end to end']]
  },
  {
    title: 'KABSAT', cat: 'WEB — LOCAL DIRECTORY', client: 'Self-initiated', year: '2023',
    role: 'Solo build', stack: ['HTML', 'CSS', 'Vanilla JS', 'Leaflet'], ui: 'website',
    desc: 'A directory for La Union\'s small businesses, from carinderias to surf shops, San Fernando to San Juan. Zero frameworks, hand-rolled map filters, and the stubborn belief that locals deserve better than Facebook pages.',
    metrics: [['40+', 'local listings'], ['0', 'frameworks used'], ['1', 'map, everything']]
  },
  {
    title: 'QUIZFORGE', cat: 'APP — STUDY TOOL', client: 'Built for exam season', year: '2023',
    role: 'Solo build', stack: ['JavaScript', 'LocalStorage', 'PWA'], ui: 'phone',
    desc: 'A reviewer app with spaced repetition that I built to survive midterms, then shared with classmates. Question banks, streak tracking, offline mode, because review centers have terrible Wi-Fi.',
    metrics: [['500+', 'questions written'], ['PWA', 'works offline'], ['3', 'majors survived']]
  },
  {
    title: 'TASKFLOW', cat: 'APP — PRODUCTIVITY', client: 'My own daily driver', year: '2024',
    role: 'Solo build', stack: ['React', 'Vite', 'dnd-kit'], ui: 'kanban',
    desc: 'A Kanban task manager I use every single day. Drag-and-drop, offline persistence, keyboard shortcuts. Built to learn React properly and to finally stop losing my own to-do lists.',
    metrics: [['365+', 'days in use'], ['60fps', 'drag & drop'], ['0', 'servers needed']]
  },
  {
    title: 'SITS ATTENDANCE', cat: 'SYSTEM — STUDENT ATTENDANCE MANAGEMENT', client: 'SITS — Academic Institution', year: '2026',
    role: 'Solo Developer', stack: ['Vanilla PHP', 'CSS', 'Bootstrap', 'PHP Backend'], ui: 'dashboard',
    shot: 'project/SITS.png',
    desc: 'A student attendance management system for SITS. Features secure login with ID number and password authentication, attendance tracking per student, administrative controls for managing records, and a clean portal for monitoring daily attendance data across classes.',
    metrics: [['100%', 'attendance tracked'], ['Secure', 'ID-based login'], ['Real-time', 'records']]
  },
  {
    title: 'ANWATCH', cat: 'WEB — ANIME STREAMING CATALOG', client: 'Self-initiated', year: '2026',
    role: 'Solo Developer', stack: ['Vanilla PHP', 'CSS', 'Bootstrap', 'PHP Backend'], ui: 'website',
    shot: 'project/Anime.png',
    desc: 'An anime browsing and catalog platform featuring 166+ titles with rich filtering options. Users can browse by sort order (Most Popular, Top Rated, Newest, A-Z, Year), filter by status (Ongoing, Completed, Upcoming) and type (TV, Movie, OVA), with star ratings and episode counts displayed on each card.',
    metrics: [['166+', 'anime titles'], ['Multi-filter', 'system'], ['PHP', 'backend']] 
  }
];

/* =========================================================
   HERO SCENES — one per IT discipline
   ========================================================= */

/* 1 — CODE RAIN (programming) */
function sceneRain() {
  let W = 0, H = 0, cols = [], fresh = true;
  return {
    wake() { fresh = true; },
    init(w, h) {
      W = w; H = h; fresh = true;
      const gap = Math.max(18, Math.round(w / 72));
      cols = [];
      for (let x = gap / 2; x < w; x += gap) {
        cols.push({ x, y: Math.random() * h, sp: (30 + Math.random() * 110) * (h / 900), len: 6 + (Math.random() * 9 | 0), hot: Math.random() < .16 });
      }
    },
    draw(ctx, t, dt) {
      if (fresh) { ctx.fillStyle = '#050505'; ctx.fillRect(0, 0, W, H); fresh = false; }
      ctx.fillStyle = 'rgba(5,5,5,0.22)'; ctx.fillRect(0, 0, W, H);
      const fs = Math.max(11, Math.round(13 * (W / 1400)));
      ctx.font = fs + 'px "JetBrains Mono", monospace';
      ctx.textAlign = 'center'; ctx.textBaseline = 'alphabetic';
      const lh = fs * 1.35;
      for (const c of cols) {
        c.y += c.sp * dt;
        if (c.y - c.len * lh > H) { c.y = -Math.random() * 300; c.hot = Math.random() < .16; }
        for (let i = 0; i < c.len; i++) {
          const y = c.y - i * lh;
          if (y < 0 || y > H + fs) continue;
          const a = Math.pow(1 - i / c.len, 1.6);
          if (i === 0 && c.hot) ctx.fillStyle = 'rgba(255,84,0,' + Math.min(1, a + .2) + ')';
          else ctx.fillStyle = c.hot ? 'rgba(200,200,200,' + (a * .55) + ')' : 'rgba(170,170,170,' + (a * .4) + ')';
          ctx.fillText(rc(), c.x, y);
        }
      }
    }
  };
}

/* 2 — NETWORK MESH (networking) */
function sceneNetwork() {
  let W = 0, H = 0, sc = 1, nodes = [], edges = [], packets = [], hubs = [], bg = null, spawnT = 0;
  const LABELS = ['ROUTER', 'SRV-DB', 'WAP-02', 'SWITCH-01', 'NAS', 'PC-LAB', 'AP-3F', 'PRINTER', 'CAM-01', 'FW-EDGE'];
  const dist2 = (a, b) => (a.x - b.x) * (a.x - b.x) + (a.y - b.y) * (a.y - b.y);
  const edgeKey = (a, b) => a.id < b.id ? a.id + '-' + b.id : b.id + '-' + a.id;
  return {
    init(w, h) {
      W = w; H = h; sc = w / 1600; nodes = []; edges = []; packets = []; hubs = []; spawnT = 0;
      const colsN = Math.max(4, Math.floor(W / (170 * sc)));
      const rowsN = Math.max(3, Math.floor(H / (170 * sc)));
      let id = 0;
      for (let r = 0; r < rowsN; r++) for (let c = 0; c < colsN; c++) {
        if (Math.random() < 0.30) continue;
        nodes.push({
          id: id++,
          x: (c + 0.5) * W / colsN + (Math.random() - 0.5) * 90 * sc,
          y: (r + 0.5) * H / rowsN + (Math.random() - 0.5) * 90 * sc,
          pulse: 0, hub: false, label: null
        });
      }
      const seen = new Set();
      nodes.forEach(n => {
        nodes.filter(m => m !== n)
          .sort((a, b) => dist2(n, a) - dist2(n, b))
          .slice(0, 2 + (Math.random() < .4 ? 1 : 0))
          .forEach(m => {
            const k = edgeKey(n, m);
            if (seen.has(k)) return;
            seen.add(k);
            edges.push({ a: n, b: m, len: Math.max(1, Math.hypot(n.x - m.x, n.y - m.y)) });
          });
      });
      const shuffled = [...nodes].sort(() => Math.random() - .5);
      hubs = shuffled.slice(0, 3);
      hubs.forEach((hb, i) => { hb.hub = true; hb.label = LABELS[i]; });
      shuffled.slice(3, 9).forEach((n, i) => { n.label = LABELS[3 + i]; });

      bg = makeCanvas(W, H);
      const g = bg.getContext('2d');
      g.fillStyle = '#050505'; g.fillRect(0, 0, W, H);
      g.fillStyle = 'rgba(200,200,200,.05)';
      for (let y = 0; y < H; y += 34 * sc) for (let x = 0; x < W; x += 34 * sc) g.fillRect(x, y, 1.5, 1.5);
      g.lineWidth = Math.max(1, sc);
      g.strokeStyle = 'rgba(200,200,200,.10)';
      edges.forEach(e => { g.beginPath(); g.moveTo(e.a.x, e.a.y); g.lineTo(e.b.x, e.b.y); g.stroke(); });
      g.font = Math.max(10, Math.round(11 * sc)) + 'px "JetBrains Mono", monospace';
      nodes.forEach(n => {
        if (n.hub) {
          g.fillStyle = '#101010'; g.fillRect(n.x - 13 * sc, n.y - 13 * sc, 26 * sc, 26 * sc);
          g.strokeStyle = 'rgba(255,122,51,.8)'; g.lineWidth = Math.max(1, sc); g.strokeRect(n.x - 13 * sc, n.y - 13 * sc, 26 * sc, 26 * sc);
          g.fillStyle = '#FF5400'; g.fillRect(n.x - 3 * sc, n.y - 3 * sc, 6 * sc, 6 * sc);
        } else {
          g.fillStyle = 'rgba(200,200,200,.4)'; g.beginPath(); g.arc(n.x, n.y, 3.2 * sc, 0, Math.PI * 2); g.fill();
        }
        if (n.label) {
          g.fillStyle = n.hub ? 'rgba(255,122,51,.75)' : 'rgba(160,160,160,.45)';
          g.fillText(n.label, n.x + 12 * sc, n.y - 10 * sc);
        }
      });
    },
    draw(ctx, t, dt) {
      if (!bg) return;
      ctx.drawImage(bg, 0, 0);
      spawnT -= dt;
      if (spawnT <= 0 && packets.length < 16 && edges.length) {
        spawnT = 0.35 + Math.random() * 0.5;
        const e = edges[(Math.random() * edges.length) | 0];
        const fwd = Math.random() < .5;
        packets.push({ e, p: fwd ? 0 : 1, dir: fwd ? 1 : -1, sp: (140 + Math.random() * 160) * sc / e.len });
      }
      hubs.forEach(hb => {
        ctx.save();
        ctx.strokeStyle = 'rgba(255,84,0,.35)'; ctx.lineWidth = 1.2;
        ctx.setLineDash([6 * sc, 6 * sc]); ctx.lineDashOffset = -t * 20 * sc;
        ctx.beginPath(); ctx.arc(hb.x, hb.y, 26 * sc, 0, Math.PI * 2); ctx.stroke();
        ctx.restore();
      });
      packets = packets.filter(pk => {
        pk.p += pk.sp * dt * pk.dir;
        if (pk.dir > 0 ? pk.p >= 1 : pk.p <= 0) {
          (pk.dir > 0 ? pk.e.b : pk.e.a).pulse = 1;
          return false;
        }
        for (let j = 1; j <= 4; j++) {
          const tp = pk.p - pk.dir * j * 0.03;
          if (tp < 0 || tp > 1) continue;
          ctx.fillStyle = 'rgba(255,84,0,' + (0.28 * (1 - j / 4)) + ')';
          ctx.beginPath();
          ctx.arc(pk.e.a.x + (pk.e.b.x - pk.e.a.x) * tp, pk.e.a.y + (pk.e.b.y - pk.e.a.y) * tp, 2.4 * sc, 0, Math.PI * 2);
          ctx.fill();
        }
        const x = pk.e.a.x + (pk.e.b.x - pk.e.a.x) * pk.p;
        const y = pk.e.a.y + (pk.e.b.y - pk.e.a.y) * pk.p;
        ctx.save();
        ctx.shadowColor = 'rgba(255,84,0,.9)'; ctx.shadowBlur = 8 * sc;
        ctx.fillStyle = '#FF5400';
        ctx.beginPath(); ctx.arc(x, y, 3 * sc + 1, 0, Math.PI * 2); ctx.fill();
        ctx.restore();
        return true;
      });
      nodes.forEach(n => {
        if (n.pulse > 0) {
          n.pulse -= dt * 1.4;
          ctx.strokeStyle = 'rgba(255,84,0,' + (n.pulse * .6) + ')';
          ctx.lineWidth = 1.5;
          ctx.beginPath(); ctx.arc(n.x, n.y, (6 + (1 - n.pulse) * 16) * sc, 0, Math.PI * 2); ctx.stroke();
        }
      });
    }
  };
}

/* 3 — CIRCUITRY (hardware) */
function sceneCircuit() {
  let W = 0, H = 0, paths = [], bgCv = null;
  function ptAt(p, d) {
    d = Math.max(0, Math.min(d, p.len));
    let k = 1;
    while (k < p.cum.length - 1 && p.cum[k] < d) k++;
    const a = p.pts[k - 1], b = p.pts[k];
    const seg = (p.cum[k] - p.cum[k - 1]) || 1;
    const f = (d - p.cum[k - 1]) / seg;
    return { x: a.x + (b.x - a.x) * f, y: a.y + (b.y - a.y) * f };
  }
  return {
    init(w, h) {
      W = w; H = h; paths = [];
      const sc = w / 1600;
      const cell = Math.max(30, Math.round(46 * sc * (w / h) * (h / w) * 46 / 46 * (46 * sc / (46 * sc)) * 1)); // cell = 46*sc scaled below
      const cc = Math.max(30, 46 * sc);
      void cell;
      const n = Math.max(8, Math.round(H / cc / 1.4) + 6);
      for (let i = 0; i < n; i++) {
        const pts = [];
        let x = -cc * (1 + Math.random() * 4);
        let y = cc * (1 + Math.floor(Math.random() * Math.max(2, H / cc - 2)));
        pts.push({ x, y });
        const steps = 3 + (Math.random() * 6 | 0);
        for (let s = 0; s < steps; s++) {
          x += cc * (2 + (Math.random() * 5 | 0));
          pts.push({ x, y });
          if (Math.random() < .65) {
            const ny = cc * (1 + Math.floor(Math.random() * Math.max(2, H / cc - 2)));
            if (ny !== y) { y = ny; pts.push({ x, y }); }
          }
        }
        x += cc * (2 + (Math.random() * 6 | 0));
        pts.push({ x, y });
        let len = 0; const cum = [0];
        for (let k = 1; k < pts.length; k++) { len += Math.hypot(pts[k].x - pts[k - 1].x, pts[k].y - pts[k - 1].y); cum.push(len); }
        paths.push({ pts, cum, len, pulses: [{ p: Math.random(), sp: .05 + Math.random() * .09 }, { p: Math.random(), sp: .05 + Math.random() * .09 }] });
      }
      bgCv = makeCanvas(W, H);
      const g = bgCv.getContext('2d');
      g.fillStyle = '#050505'; g.fillRect(0, 0, W, H);
      g.fillStyle = 'rgba(200,200,200,.05)';
      for (let gy = cc; gy < H; gy += cc) for (let gx = cc; gx < W; gx += cc) g.fillRect(gx - 1, gy - 1, 2, 2);
      g.lineWidth = Math.max(1, W / 1600); g.strokeStyle = 'rgba(200,200,200,.12)';
      for (const p of paths) {
        g.beginPath(); g.moveTo(p.pts[0].x, p.pts[0].y);
        for (let k = 1; k < p.pts.length; k++) g.lineTo(p.pts[k].x, p.pts[k].y);
        g.stroke();
      }
      g.fillStyle = 'rgba(200,200,200,.28)';
      for (const p of paths) for (const q of p.pts) g.fillRect(q.x - 1.5, q.y - 1.5, 3, 3);
      for (let i = 0; i < Math.max(4, n / 3 | 0); i++) {
        const p = paths[(Math.random() * paths.length) | 0];
        const q = p.pts[1 + (Math.random() * (p.pts.length - 2) | 0)];
        const w2 = cc * 1.6, h2 = cc * 1.1;
        g.strokeStyle = 'rgba(255,84,0,.35)'; g.lineWidth = 1;
        g.strokeRect(q.x - w2 / 2, q.y - h2 / 2, w2, h2);
        g.fillStyle = 'rgba(255,84,0,.08)';
        g.fillRect(q.x - w2 / 2, q.y - h2 / 2, w2, h2);
        g.fillStyle = 'rgba(255,122,51,.5)';
        for (let pk = 0; pk < 4; pk++) {
          g.fillRect(q.x - w2 / 2 + (pk + 0.5) * (w2 / 4) - 1, q.y - h2 / 2 - 4, 2, 4);
          g.fillRect(q.x - w2 / 2 + (pk + 0.5) * (w2 / 4) - 1, q.y + h2 / 2, 2, 4);
        }
      }
    },
    draw(ctx, t, dt) {
      if (!bgCv) return;
      ctx.drawImage(bgCv, 0, 0);
      const sc = Math.max(1, W / 1400);
      for (const p of paths) for (const pu of p.pulses) {
        pu.p += pu.sp * dt;
        if (pu.p > 1.1) { pu.p = -Math.random() * .35; pu.sp = .05 + Math.random() * .09; }
        if (pu.p < 0) continue;
        const d = pu.p * p.len;
        for (let j = 5; j >= 1; j--) {
          const dd = d - j * 9 * sc;
          if (dd < 0) continue;
          const tp = ptAt(p, dd);
          ctx.fillStyle = 'rgba(255,84,0,' + (.30 * (1 - j / 5)) + ')';
          ctx.fillRect(tp.x - 1.5 * sc, tp.y - 1.5 * sc, 3 * sc, 3 * sc);
        }
        const pos = ptAt(p, d);
        ctx.save();
        ctx.shadowColor = 'rgba(255,84,0,.9)'; ctx.shadowBlur = 10 * sc;
        ctx.fillStyle = '#FF5400';
        ctx.beginPath(); ctx.arc(pos.x, pos.y, 2.2 * sc + 1, 0, Math.PI * 2); ctx.fill();
        ctx.restore();
      }
    }
  };
}

/* 4 — DATA PULSE (data / analytics oscilloscope) */
function sceneWave() {
  let W = 0, H = 0, sc = 1, bg = null;
  const waves = [
    { amp: .16, f: .006, sp: 1.6, ph: 0,   col: 'rgba(200,200,200,.55)', lw: 1.6 },
    { amp: .24, f: .004, sp: -1.1, ph: 2.1, col: 'rgba(255,84,0,.85)',   lw: 2.2 },
    { amp: .10, f: .010, sp: 2.4, ph: 4.4,  col: 'rgba(255,122,51,.40)', lw: 1.2 },
  ];
  return {
    init(w, h) {
      W = w; H = h; sc = w / 1600;
      bg = makeCanvas(W, H);
      const g = bg.getContext('2d');
      g.fillStyle = '#050505'; g.fillRect(0, 0, W, H);
      const gs = 44 * sc;
      g.strokeStyle = 'rgba(255,255,255,.045)'; g.lineWidth = 1;
      for (let x = 0; x <= W; x += gs) { g.beginPath(); g.moveTo(x, 0); g.lineTo(x, H); g.stroke(); }
      for (let y = 0; y <= H; y += gs) { g.beginPath(); g.moveTo(0, y); g.lineTo(W, y); g.stroke(); }
      g.strokeStyle = 'rgba(255,255,255,.09)';
      g.beginPath(); g.moveTo(0, H / 2); g.lineTo(W, H / 2); g.stroke();
      g.beginPath(); g.moveTo(W / 2, 0); g.lineTo(W / 2, H); g.stroke();
      g.fillStyle = 'rgba(255,255,255,.14)';
      for (let x = 0; x <= W; x += gs) g.fillRect(x - 1, H / 2 - 4 * sc, 2, 8 * sc);
      g.font = Math.max(10, 11 * sc) + 'px "JetBrains Mono", monospace';
      g.fillStyle = 'rgba(255,122,51,.8)';
      g.fillText('CH 1 — SYSTEM LOAD', 24 * sc, H - 44 * sc);
      g.fillStyle = 'rgba(160,160,160,.5)';
      g.fillText('CH 2 — QUERIES/S', 24 * sc, H - 44 * sc + 16 * sc);
      g.textAlign = 'right';
      g.fillText('SAMPLE 44.1 kHz · 60 FPS', W - 24 * sc, H - 44 * sc);
      g.textAlign = 'left';
    },
    draw(ctx, t, dt) {
      if (!bg) return;
      ctx.drawImage(bg, 0, 0);
      const step = 4 * sc;
      waves.forEach(wv => {
        ctx.beginPath();
        for (let x = 0; x <= W; x += step) {
          const mod = 0.72 + 0.28 * Math.sin(t * 0.35 + wv.ph * 1.7);
          const y = H / 2 + Math.sin(x * wv.f + t * wv.sp + wv.ph) * H * wv.amp * mod;
          x === 0 ? ctx.moveTo(x, y) : ctx.lineTo(x, y);
        }
        ctx.strokeStyle = wv.col;
        ctx.lineWidth = Math.max(1, wv.lw * sc * 1.2);
        ctx.stroke();
      });
      const n = Math.floor(W / (22 * sc));
      for (let i = 0; i < n; i++) {
        const v = 0.25 + 0.75 * Math.abs(Math.sin(t * 2.1 + i * 0.35) * Math.sin(t * 0.6 + i * 0.13));
        const bh = v * H * 0.12;
        ctx.fillStyle = i % 9 === 3 ? 'rgba(255,84,0,.75)' : 'rgba(200,200,200,.22)';
        ctx.fillRect(i * 22 * sc + 6 * sc, H * 0.86 - bh, 10 * sc, bh);
      }
      ctx.font = Math.max(10, 11 * sc) + 'px "JetBrains Mono", monospace';
      ctx.textAlign = 'right';
      ctx.fillStyle = 'rgba(255,122,51,.9)';
      ctx.fillText('CH1 ' + ((Math.sin(t * 1.3) * 0.5 + 0.5) * 4.8 + 3.1).toFixed(2) + 'V', W - 24 * sc, 40 * sc);
      ctx.fillStyle = 'rgba(160,160,160,.55)';
      ctx.fillText('DB ' + Math.round((Math.sin(t * 0.8 + 2) * 0.5 + 0.5) * 940 + 60) + ' q/s', W - 24 * sc, 40 * sc + 16 * sc);
      ctx.textAlign = 'left';
    }
  };
}

/* 5 — UI BLUEPRINT (design / front-end) */
function sceneUI() {
  let W = 0, H = 0, sc = 1, bg = null, blocks = [], sel = 0, selT = 0, ripples = [], clickT = 0;
  return {
    init(w, h) {
      W = w; H = h; sc = w / 1600; blocks = []; ripples = []; sel = 0; selT = 0; clickT = 0.8;
      const fx = 120 * sc, fy = 110 * sc, fw = W - 260 * sc, fh = H - 180 * sc;
      const px0 = fx + 24 * sc, pw2 = fw - 48 * sc;
      const nav = { x: px0, y: fy + 22 * sc, w: pw2, h: 52 * sc, label: 'NAV — MENU / CTA' };
      const heroY = nav.y + nav.h + 26 * sc;
      const hero = { x: px0, y: heroY, w: pw2 * 0.56, h: 112 * sc, label: 'HERO' };
      const feat = { x: px0 + hero.w + 22 * sc, y: heroY, w: pw2 - hero.w - 22 * sc, h: 112 * sc, label: 'FEATURE' };
      const cta = { x: px0, y: heroY + hero.h + 22 * sc, w: 150 * sc, h: 44 * sc, label: 'CTA', accent: true };
      blocks = [nav, hero, feat, cta];
      const cardY = cta.y + cta.h + 26 * sc;
      const footer = { x: px0, y: fy + fh - 64 * sc, w: pw2, h: 44 * sc, label: 'FOOTER' };
      if (footer.y - (cardY + 96 * sc) > 24 * sc) {
        const cw3 = (pw2 - 44 * sc) / 3;
        for (let k = 0; k < 3; k++) blocks.push({ x: px0 + k * (cw3 + 22 * sc), y: cardY, w: cw3, h: 96 * sc, label: 'CARD 0' + (k + 1) });
      }
      blocks.push(footer);

      bg = makeCanvas(W, H);
      const g = bg.getContext('2d');
      g.fillStyle = '#0c0c0c'; g.fillRect(0, 0, W, H);
      g.fillStyle = 'rgba(255,255,255,.05)';
      for (let y = 44 * sc; y < H; y += 26 * sc) for (let x = 44 * sc; x < W; x += 26 * sc) g.fillRect(x, y, 1.5, 1.5);
      g.fillStyle = '#0b0b0b'; g.fillRect(0, 0, W, 26 * sc); g.fillRect(0, 0, 26 * sc, H);
      g.fillStyle = 'rgba(255,255,255,.22)';
      for (let x = 26 * sc; x < W; x += 26 * sc) {
        const big = Math.round((x - 26 * sc) / sc) % 104 === 0;
        g.fillRect(x, 26 * sc - (big ? 9 * sc : 4 * sc), 1, big ? 9 * sc : 4 * sc);
        if (big) txt(g, String(Math.round(x / sc)), x + 3 * sc, 14 * sc, '9px "JetBrains Mono", monospace', 'rgba(255,255,255,.25)');
      }
      for (let y = 26 * sc; y < H; y += 26 * sc) {
        const big = Math.round((y - 26 * sc) / sc) % 104 === 0;
        g.fillRect(26 * sc - (big ? 9 * sc : 4 * sc), y, big ? 9 * sc : 4 * sc, 1);
      }
      g.strokeStyle = 'rgba(255,255,255,.22)'; g.lineWidth = 1.5;
      g.strokeRect(fx, fy, fw, fh); g.lineWidth = 1;
      g.fillStyle = '#FF5400'; g.fillRect(fx, fy - 15 * sc, 8 * sc, 8 * sc);
      txt(g, 'FRAME — DESKTOP 1440 × 900', fx + 14 * sc, fy - 8 * sc, '10px "JetBrains Mono", monospace', 'rgba(255,122,51,.8)');
      blocks.forEach(b => {
        if (b.accent) {
          g.fillStyle = 'rgba(255,84,0,.15)'; g.fillRect(b.x, b.y, b.w, b.h);
          g.strokeStyle = 'rgba(255,84,0,.55)';
        } else {
          g.fillStyle = 'rgba(255,255,255,.035)'; g.fillRect(b.x, b.y, b.w, b.h);
          g.strokeStyle = 'rgba(255,255,255,.13)';
        }
        g.strokeRect(b.x, b.y, b.w, b.h);
        txt(g, b.label, b.x + 10 * sc, b.y + 16 * sc, '10px "JetBrains Mono", monospace', 'rgba(160,160,160,.55)');
      });
    },
    draw(ctx, t, dt) {
      if (!bg) return;
      ctx.drawImage(bg, 0, 0);
      selT += dt;
      if (selT > 2.4) { selT = 0; sel = (sel + 1) % blocks.length; }
      const b = blocks[sel];
      ctx.save();
      ctx.strokeStyle = '#FF5400'; ctx.lineWidth = 1.5;
      ctx.setLineDash([7 * sc, 5 * sc]); ctx.lineDashOffset = -t * 30 * sc;
      ctx.strokeRect(b.x - 6 * sc, b.y - 6 * sc, b.w + 12 * sc, b.h + 12 * sc);
      ctx.restore();
      [[b.x - 6 * sc, b.y - 6 * sc], [b.x + b.w + 6 * sc, b.y - 6 * sc],
       [b.x - 6 * sc, b.y + b.h + 6 * sc], [b.x + b.w + 6 * sc, b.y + b.h + 6 * sc]].forEach(hp => {
        ctx.fillStyle = '#FF5400'; ctx.fillRect(hp[0] - 3 * sc, hp[1] - 3 * sc, 6 * sc, 6 * sc);
      });
      txt(ctx, Math.round(b.w / sc) + ' × ' + Math.round(b.h / sc), b.x + b.w + 12 * sc, b.y + b.h + 4 * sc, '10px "JetBrains Mono", monospace', '#FF7A33');
      const fx = 120 * sc, fy = 110 * sc, fw = W - 260 * sc, fh = H - 180 * sc;
      const cxp = fx + fw * (0.5 + 0.36 * Math.sin(t * 0.42));
      const cyp = fy + fh * (0.5 + 0.34 * Math.sin(t * 0.63 + 1.4));
      clickT -= dt;
      if (clickT <= 0) { clickT = 1.6 + Math.random() * 1.4; ripples.push({ x: cxp, y: cyp, r: 0 }); }
      ripples = ripples.filter(rp => {
        rp.r += dt * 120 * sc;
        const a = 1 - rp.r / (46 * sc);
        if (a <= 0) return false;
        ctx.strokeStyle = 'rgba(255,84,0,' + (a * .7) + ')';
        ctx.beginPath(); ctx.arc(rp.x, rp.y, rp.r, 0, Math.PI * 2); ctx.stroke();
        return true;
      });
      drawCursorShape(ctx, cxp, cyp, 1.4 * sc);
    }
  };
}

/* 6 — CIPHER RADAR (cybersecurity) */
function sceneCipher() {
  let W = 0, H = 0, sc = 1, bg = null, pairs = [], hotRow = -1, hotCol = -1, mutT = 0;
  let sweepA = 0, blips = [], spawnT = 0, prog = 0;
  const hex2 = () => ((Math.random() * 256) | 0).toString(16).padStart(2, '0').toUpperCase();
  return {
    init(w, h) {
      W = w; H = h; sc = w / 1600;
      const rows = Math.min(18, Math.max(6, Math.floor(H / (54 * sc))));
      const cols = 8;
      pairs = Array.from({ length: rows }, () => Array.from({ length: cols }, hex2));
      hotRow = (Math.random() * rows) | 0; hotCol = (Math.random() * cols) | 0;
      blips = []; spawnT = 0; sweepA = 0; prog = 0; mutT = 0;
      const cx = W * 0.68, cy = H * 0.52, R = Math.min(H * 0.36, W * 0.22);
      bg = makeCanvas(W, H);
      const g = bg.getContext('2d');
      g.fillStyle = '#050505'; g.fillRect(0, 0, W, H);
      g.font = Math.max(10, 11 * sc) + 'px "JetBrains Mono", monospace';
      g.fillStyle = 'rgba(255,122,51,.85)';
      g.fillText('INTERCEPTED PAYLOAD — AES-256', 40 * sc, 52 * sc);
      g.fillStyle = 'rgba(160,160,160,.5)';
      g.fillText('SESSION ' + Math.random().toString(16).slice(2, 8).toUpperCase(), 40 * sc, 52 * sc + 18 * sc);
      [0.25, 0.5, 0.75, 1].forEach(f => {
        g.strokeStyle = 'rgba(200,200,200,.14)'; g.lineWidth = 1;
        g.beginPath(); g.arc(cx, cy, R * f, 0, Math.PI * 2); g.stroke();
      });
      g.strokeStyle = 'rgba(200,200,200,.10)';
      g.beginPath(); g.moveTo(cx - R, cy); g.lineTo(cx + R, cy); g.moveTo(cx, cy - R); g.lineTo(cx, cy + R); g.stroke();
      for (let a = 0; a < 360; a += 30) {
        const rad = a * Math.PI / 180;
        g.beginPath();
        g.moveTo(cx + Math.cos(rad) * R, cy + Math.sin(rad) * R);
        g.lineTo(cx + Math.cos(rad) * (R - 8 * sc), cy + Math.sin(rad) * (R - 8 * sc));
        g.strokeStyle = 'rgba(200,200,200,.25)'; g.stroke();
      }
      const s = 16 * sc;
      g.strokeStyle = 'rgba(255,84,0,.9)'; g.lineWidth = 2 * sc;
      g.beginPath(); g.arc(cx, cy - s * 0.4, s * 0.5, Math.PI, 0); g.stroke();
      g.fillStyle = '#101010';
      g.fillRect(cx - s * 0.7, cy - s * 0.4, s * 1.4, s * 1.1);
      g.strokeRect(cx - s * 0.7, cy - s * 0.4, s * 1.4, s * 1.1);
      g.fillStyle = '#FF5400'; g.fillRect(cx - 2.5 * sc, cy + 0.2 * s, 5 * sc, 6 * sc);
      g.lineWidth = 1;
      g.fillStyle = 'rgba(160,160,160,.5)';
      g.fillText('THREAT RADAR — 360°', cx - 70 * sc, cy + R + 28 * sc);
    },
    draw(ctx, t, dt) {
      if (!bg) return;
      ctx.drawImage(bg, 0, 0);
      const cx = W * 0.68, cy = H * 0.52, R = Math.min(H * 0.36, W * 0.22);
      sweepA += dt * 1.1;
      const a = sweepA % (Math.PI * 2);
      ctx.save();
      ctx.translate(cx, cy); ctx.rotate(a);
      for (let k = 0; k < 14; k++) {
        const aa = -k * 0.035;
        ctx.strokeStyle = 'rgba(255,84,0,' + (0.16 * (1 - k / 14)) + ')';
        ctx.lineWidth = 3 * sc;
        ctx.beginPath(); ctx.moveTo(0, 0); ctx.lineTo(Math.cos(aa) * R, Math.sin(aa) * R); ctx.stroke();
      }
      ctx.strokeStyle = 'rgba(255,84,0,.9)'; ctx.lineWidth = 2;
      ctx.beginPath(); ctx.moveTo(0, 0); ctx.lineTo(R, 0); ctx.stroke();
      ctx.restore();
      spawnT -= dt;
      if (spawnT <= 0) {
        spawnT = 0.5 + Math.random() * 0.8;
        blips.push({ a: Math.random() * Math.PI * 2, r: R * (0.2 + Math.random() * 0.75), life: 0, seen: 0 });
      }
      blips = blips.filter(b => {
        b.life += dt;
        const diff = ((a - b.a) % (Math.PI * 2) + Math.PI * 2) % (Math.PI * 2);
        if (diff < 0.12) b.seen = 1;
        b.seen = Math.max(0, b.seen - dt * 0.35);
        if (b.life > 7) return false;
        const x = cx + Math.cos(b.a) * b.r, y = cy + Math.sin(b.a) * b.r;
        ctx.fillStyle = 'rgba(255,122,51,' + Math.max(0.08, b.seen * 0.9) + ')';
        ctx.beginPath(); ctx.arc(x, y, 3.5 * sc, 0, Math.PI * 2); ctx.fill();
        if (b.seen > 0.4) {
          ctx.strokeStyle = 'rgba(255,84,0,' + (b.seen * 0.5) + ')';
          ctx.beginPath(); ctx.arc(x, y, (8 + (1 - b.seen) * 14) * sc, 0, Math.PI * 2); ctx.stroke();
        }
        return true;
      });
      mutT -= dt;
      if (mutT <= 0) {
        mutT = 0.18;
        for (let k = 0; k < 4; k++) pairs[(Math.random() * pairs.length) | 0][(Math.random() * 8) | 0] = hex2();
        hotRow = (Math.random() * pairs.length) | 0;
        hotCol = (Math.random() * 8) | 0;
      }
      const startY = 92 * sc, colW = 66 * sc, stepY = 54 * sc, startX = 40 * sc;
      ctx.font = Math.max(10, 12 * sc) + 'px "JetBrains Mono", monospace';
      for (let r = 0; r < pairs.length; r++) for (let c = 0; c < 8; c++) {
        ctx.fillStyle = (r === hotRow && c === hotCol) ? 'rgba(255,122,51,.9)' : 'rgba(160,160,160,.32)';
        ctx.fillText(pairs[r][c], startX + c * colW, startY + r * stepY);
      }
      prog += dt * 4.3;
      const pct = (prog % 100).toFixed(1);
      txt(ctx, 'BRUTE-FORCE ' + pct + '%', 40 * sc, H - 34 * sc, Math.max(10, 10 * sc) + 'px "JetBrains Mono", monospace', 'rgba(160,160,160,.5)');
      ctx.strokeStyle = '#2a2a2a'; ctx.strokeRect(40 * sc, H - 26 * sc, 280 * sc, 6 * sc);
      ctx.fillStyle = '#FF5400'; ctx.fillRect(40 * sc, H - 26 * sc, 280 * sc * (prog % 100) / 100, 6 * sc);
    }
  };
}

/* ---------- Scene wiring ---------- */
const frames = [...document.querySelectorAll('.reel-frame')];
const hero = document.getElementById('hero');
const SCENE_NAMES = ['CODE RAIN', 'NETWORK MESH', 'CIRCUITRY', 'DATA PULSE', 'UI BLUEPRINT', 'CIPHER RADAR'];
const SCENES = [sceneRain(), sceneNetwork(), sceneCircuit(), sceneWave(), sceneUI(), sceneCipher()];
const ctxs = [];
let sceneReady = false;

function setupScenes() {
  const DPR = Math.min(window.devicePixelRatio || 1, 1.75);
  const w = Math.max(2, Math.round(hero.clientWidth * DPR));
  const h = Math.max(2, Math.round(hero.clientHeight * DPR));
  frames.forEach((f, i) => {
    const cv = f.querySelector('canvas');
    cv.width = w; cv.height = h;
    ctxs[i] = cv.getContext('2d');
    SCENES[i].init(w, h);
  });
  sceneReady = true;
  if (reduceMotion) SCENES.forEach((s, i) => s.draw(ctxs[i], 0, 0));
}
let rzT;
addEventListener('resize', () => { clearTimeout(rzT); rzT = setTimeout(setupScenes, 200); });

/* =========================================================
   GENERATED PROJECT MOCKUPS — 6 different UI types
   ========================================================= */
const preview = document.getElementById('workPreview');
const vpImg = document.getElementById('vpImg');
const vpTag = document.getElementById('vpTag');
const FALLBACK_IMG = 'data:image/svg+xml;charset=utf-8,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'800\' height=\'600\'%3E%3Crect width=\'800\' height=\'600\' fill=\'%230b0b0b\'/%3E%3Ctext x=\'400\' y=\'300\' fill=\'%23FF5400\' font-family=\'monospace\' font-size=\'24\' text-anchor=\'middle\'%3ERENDERING…%3C/text%3E%3C/svg%3E';
vpImg.src = FALLBACK_IMG;
document.getElementById('mImg').src = FALLBACK_IMG;
document.querySelectorAll('img[data-ii]').forEach(im => { im.src = FALLBACK_IMG; });

function shotChrome(g, W, H, title, sub) {
  g.fillStyle = '#0b0b0b'; g.fillRect(0, 0, W, H);
  const barH = 46;
  g.fillStyle = '#101010'; g.fillRect(0, 0, W, barH);
  g.fillStyle = '#FF5400'; g.fillRect(0, barH, W, 2);
  ['#e5484d', '#d4a53a', '#4cc38a'].forEach((col, k) => {
    g.fillStyle = col; g.beginPath(); g.arc(24 + k * 20, 23, 5.5, 0, Math.PI * 2); g.fill();
  });
  txt(g, title, 86, 28, '13px "JetBrains Mono", monospace', '#d8d8d8');
  txt(g, sub, W - 18, 28, '12px "JetBrains Mono", monospace', '#5a5a5a', 'right');
  return barH;
}
function shotFooter(g, W, H, left, right) {
  g.fillStyle = '#0d0d0d'; g.fillRect(0, H - 30, W, 30);
  g.fillStyle = '#1c1c1c'; g.fillRect(0, H - 30, W, 1);
  txt(g, left, 18, H - 11, '11px "JetBrains Mono", monospace', '#FF7A33');
  txt(g, right, W - 18, H - 11, '11px "JetBrains Mono", monospace', '#7a7a7a', 'right');
}
function shotFinish(g, W, H, from) {
  g.fillStyle = 'rgba(0,0,0,.13)';
  for (let y = from; y < H - 30; y += 4) g.fillRect(0, y, W, 1);
  const vg = g.createRadialGradient(W / 2, H / 2, H * .35, W / 2, H / 2, W * .72);
  vg.addColorStop(0, 'rgba(0,0,0,0)'); vg.addColorStop(1, 'rgba(0,0,0,.5)');
  g.fillStyle = vg; g.fillRect(0, 0, W, H);
}

/* — 1: admin dashboard — */
function shotDashboard(p) {
  const W = 1000, H = 760, c = makeCanvas(W, H), g = c.getContext('2d');
  const barH = shotChrome(g, W, H, 'LOUISGRADE — ADMIN PANEL', 'vince@admin · sy 2026-2027');
  const sbW = 192;
  g.fillStyle = '#0d0d0d'; g.fillRect(0, barH + 2, sbW, H - barH - 32);
  g.fillStyle = '#1c1c1c'; g.fillRect(sbW, barH + 2, 1, H - barH - 32);
  g.fillStyle = '#FF5400'; g.fillRect(18, barH + 20, 28, 28);
  txt(g, 'LG', 24, barH + 39, '700 14px Oswald, Arial', '#000');
  ['DASHBOARD', 'STUDENTS', 'SUBJECTS', 'GRADES', 'REPORTS', 'SETTINGS'].forEach((m, i) => {
    const y = barH + 86 + i * 40, active = i === 1;
    if (active) { g.fillStyle = 'rgba(255,84,0,.10)'; g.fillRect(0, y - 13, sbW, 32); g.fillStyle = '#FF5400'; g.fillRect(0, y - 13, 3, 32); }
    txt(g, m, 26, y + 3, '12px "JetBrains Mono", monospace', active ? '#FF7A33' : '#8a8a8a');
  });
  txt(g, 'STUDENT RECORDS — SY 2026–2027', sbW + 26, barH + 44, '700 18px Oswald, Arial', '#f0f0f0');
  g.strokeStyle = '#2a2a2a'; g.strokeRect(sbW + 26, barH + 56, 230, 26);
  txt(g, 'SEARCH NAME / ID…', sbW + 38, barH + 73, '11px "JetBrains Mono", monospace', '#5a5a5a');
  g.strokeStyle = '#2a2a2a'; g.strokeRect(W - 160, barH + 56, 120, 26);
  txt(g, 'EXPORT ▾', W - 146, barH + 73, '11px "JetBrains Mono", monospace', '#c8c8c8');
  const tx = sbW + 26, tw = W - tx - 26, ty = barH + 104;
  const colsX = [tx + 12, tx + 112, tx + 322, tx + 432, tx + 506, tx + 600];
  const heads = ['ID', 'NAME', 'PROGRAM', 'AVERAGE', 'GRADE', 'REMARKS'];
  g.fillStyle = '#161616'; g.fillRect(tx, ty, tw, 30);
  heads.forEach((h2, i) => txt(g, h2, colsX[i], ty + 20, '11px "JetBrains Mono", monospace', '#8a8a8a'));
  const data = [
    ['2022-0143', 'DELA CRUZ, JOSHUA', 'BSIT-3', '94.50', '1.00', 'PASSED'],
    ['2022-0144', 'SANTOS, MARIA', 'BSIT-3', '91.25', '1.25', 'PASSED'],
    ['2022-0145', 'REYES, PAOLO', 'BSIT-3', '88.00', '1.50', 'PASSED'],
    ['2022-0147', 'GARCIA, ANGELA', 'BSIT-3', '85.75', '1.75', 'PASSED'],
    ['2022-0149', 'MENDOZA, KARL', 'BSIT-3', '83.00', '2.00', 'PASSED'],
    ['2022-0151', 'TORRES, LIWA', 'BSIT-3', '74.50', '2.75', 'PASSED'],
    ['2022-0153', 'ORTEGA, MIGUEL', 'BSIT-3', '68.00', '3.25', 'FAILED'],
    ['2022-0156', 'FERNANDEZ, BEA', 'BSIT-3', '96.00', '1.00', 'PASSED'],
  ];
  data.forEach((row, ri) => {
    const y = ty + 30 + ri * 38;
    if (ri % 2 === 0) { g.fillStyle = 'rgba(255,255,255,.025)'; g.fillRect(tx, y, tw, 38); }
    g.fillStyle = '#1c1c1c'; g.fillRect(tx, y + 38, tw, 1);
    txt(g, row[0], colsX[0], y + 24, '12px "JetBrains Mono", monospace', '#6a6a6a');
    txt(g, row[1], colsX[1], y + 24, '12px "JetBrains Mono", monospace', '#d8d8d8');
    txt(g, row[2], colsX[2], y + 24, '12px "JetBrains Mono", monospace', '#9a9a9a');
    txt(g, row[3], colsX[3], y + 24, '12px "JetBrains Mono", monospace', '#d8d8d8');
    const grade = row[4], bx = colsX[4] - 4, by = y + 9;
    let gcol;
    if (grade === '1.00') { g.fillStyle = '#FF5400'; g.fillRect(bx, by, 44, 20); gcol = '#000'; }
    else if (grade[0] === '1') { g.strokeStyle = '#FF7A33'; g.strokeRect(bx, by, 44, 20); gcol = '#FF7A33'; }
    else { g.strokeStyle = '#555'; g.strokeRect(bx, by, 44, 20); gcol = '#8a8a8a'; }
    txt(g, grade, bx + 13, by + 14, '11px "JetBrains Mono", monospace', gcol);
    const pass = row[5] === 'PASSED';
    g.strokeStyle = pass ? 'rgba(76,195,138,.5)' : 'rgba(229,72,77,.6)';
    g.strokeRect(colsX[5] - 4, y + 9, 74, 20);
    txt(g, row[5], colsX[5] + 14, y + 23, '10px "JetBrains Mono", monospace', pass ? '#4cc38a' : '#e5484d');
  });
  shotFooter(g, W, H, 'RECORDS: 312 · SHOWING 8', 'MYSQL · LIVE');
  shotFinish(g, W, H, barH);
  return c.toDataURL('image/jpeg', .85);
}

/* — 2: request queue + audit trail — */
function shotQueue(p) {
  const W = 1000, H = 760, c = makeCanvas(W, H), g = c.getContext('2d');
  const barH = shotChrome(g, W, H, 'PUROKCONNECT — REQUEST QUEUE', 'brgy.sflu · purok 4');
  txt(g, 'CLEARANCE REQUESTS', 24, barH + 46, '700 20px Oswald, Arial', '#f0f0f0');
  const chips = [['TODAY', '12'], ['PENDING', '4'], ['APPROVED', '8'], ['AVG TIME', '5 MIN']];
  chips.forEach((ch, i) => {
    const x = 24 + i * 148, y = barH + 62;
    g.strokeStyle = '#2a2a2a'; g.strokeRect(x, y, 132, 44);
    txt(g, ch[0], x + 12, y + 18, '9px "JetBrains Mono", monospace', '#6a6a6a');
    txt(g, ch[1], x + 12, y + 36, '700 16px Oswald, Arial', '#FF7A33');
  });
  const reqs = [
    ['BARANGAY CLEARANCE', 'R. DELA PEÑA — PUROK 4', '08:41 AM', 'PENDING', 1],
    ['CERT. OF RESIDENCY', 'M. SORIANO — PUROK 2', '09:02 AM', 'REVIEW', 2],
    ['BARANGAY CLEARANCE', 'J. LUCERO — PUROK 7', '09:15 AM', 'APPROVED', 3],
    ['BUSINESS PERMIT', 'A. MANALO — PUROK 1', '09:31 AM', 'APPROVED', 3],
  ];
  const rx = 24, rw = 590, ry0 = barH + 126;
  reqs.forEach((rq, i) => {
    const y = ry0 + i * 108;
    g.fillStyle = '#111'; g.fillRect(rx, y, rw, 96);
    g.strokeStyle = '#222'; g.strokeRect(rx, y, rw, 96);
    txt(g, rq[0], rx + 16, y + 26, '700 15px Oswald, Arial', '#e8e8e8');
    txt(g, rq[1], rx + 16, y + 46, '11px "JetBrains Mono", monospace', '#7a7a7a');
    txt(g, rq[2], rx + 16, y + 66, '10px "JetBrains Mono", monospace', '#555');
    const st = rq[3], sx = rx + rw - 118, sy = y + 16;
    let stCol;
    if (st === 'APPROVED') { g.fillStyle = '#FF5400'; g.fillRect(sx, sy, 100, 26); stCol = '#000'; }
    else if (st === 'REVIEW') { g.strokeStyle = '#FF7A33'; g.strokeRect(sx, sy, 100, 26); stCol = '#FF7A33'; }
    else { g.strokeStyle = '#555'; g.strokeRect(sx, sy, 100, 26); stCol = '#9a9a9a'; }
    txt(g, st, sx + (st === 'APPROVED' ? 30 : 34), sy + 17, '10px "JetBrains Mono", monospace', stCol);
    const labels = ['FILED', 'REVIEW', 'DONE'];
    labels.forEach((L, k) => {
      const sxp = rx + rw - 330 + k * 105, syp = y + 72;
      if (k < rq[4]) { g.fillStyle = '#FF5400'; g.beginPath(); g.arc(sxp, syp, 5, 0, Math.PI * 2); g.fill(); }
      else { g.strokeStyle = '#333'; g.beginPath(); g.arc(sxp, syp, 5, 0, Math.PI * 2); g.stroke(); }
      if (k < 2) {
        g.strokeStyle = k < rq[4] - 1 ? '#FF5400' : '#2a2a2a';
        g.beginPath(); g.moveTo(sxp + 12, syp); g.lineTo(sxp + 93, syp); g.stroke();
      }
      txt(g, L, sxp - 14, syp + 18, '8px "JetBrains Mono", monospace', '#666');
    });
  });
  const ax = 640, aw = 336;
  g.fillStyle = '#0d0d0d'; g.fillRect(ax, barH + 126, aw, H - barH - 190);
  g.strokeStyle = '#1f1f1f'; g.strokeRect(ax, barH + 126, aw, H - barH - 190);
  txt(g, 'AUDIT TRAIL', ax + 16, barH + 152, '11px "JetBrains Mono", monospace', '#FF7A33');
  const log = [
    ['09:41', '#1128 APPROVED', 'KGD. REYES'],
    ['09:12', '#1127 → REVIEW', 'BRGY CAPT.'],
    ['08:55', '#1127 FILED', 'M. SORIANO'],
    ['08:47', 'RESIDENT VERIFIED', 'SYSTEM'],
    ['08:31', '#1126 APPROVED', 'KGD. REYES'],
    ['08:02', '#1125 APPROVED', 'TREASURER'],
    ['07:48', '#1125 FILED', 'A. MANALO'],
  ];
  log.forEach((L, i) => {
    const y = barH + 184 + i * 40;
    txt(g, L[0], ax + 16, y, '10px "JetBrains Mono", monospace', '#555');
    txt(g, L[1], ax + 70, y, '11px "JetBrains Mono", monospace', i === 0 ? '#FF7A33' : '#c8c8c8');
    txt(g, L[2], ax + 16, y + 15, '9px "JetBrains Mono", monospace', '#666');
  });
  shotFooter(g, W, H, 'QUEUE: LIVE · AUDIT: IMMUTABLE', 'MYSQL · PHP');
  shotFinish(g, W, H, barH);
  return c.toDataURL('image/jpeg', .85);
}

/* — 3: website / directory with map — */
function shotWebsite(p) {
  const W = 1000, H = 760, c = makeCanvas(W, H), g = c.getContext('2d');
  const barH = shotChrome(g, W, H, 'KABSAT — LOCAL DIRECTORY', 'kabsat.ph/la-union');
  txt(g, 'KABSAT', 24, barH + 92, '84px "Bebas Neue", Arial', '#f0f0f0');
  txt(g, 'LA UNION, ON ONE MAP', 24, barH + 126, '26px "Bebas Neue", Arial', '#FF5400');
  txt(g, 'every carinderia, surf shop & sari-sari store — pinned by locals', 24, barH + 150, '12px "JetBrains Mono", monospace', '#9a9a9a');
  g.fillStyle = '#FF5400'; g.fillRect(24, barH + 168, 150, 36);
  txt(g, 'BROWSE SHOPS', 44, barH + 191, '12px "JetBrains Mono", monospace', '#000');
  g.strokeStyle = '#3a3a3a'; g.strokeRect(190, barH + 168, 150, 36);
  txt(g, 'SUBMIT LISTING', 210, barH + 191, '12px "JetBrains Mono", monospace', '#c8c8c8');
  const towns = ['ALL', 'SAN FERNANDO', 'AGOO', 'ARINGAY', 'BAUANG', 'SAN JUAN'];
  let chx = 24;
  towns.forEach((tn, i) => {
    const w2 = tn.length * 7.5 + 24;
    if (i === 0) { g.fillStyle = '#FF5400'; g.fillRect(chx, barH + 228, w2, 28); }
    else { g.strokeStyle = '#333'; g.strokeRect(chx, barH + 228, w2, 28); }
    txt(g, tn, chx + 12, barH + 247, '10px "JetBrains Mono", monospace', i === 0 ? '#000' : '#9a9a9a');
    chx += w2 + 10;
  });
  const cards = [
    ['EAT', 'ALING ROSA CARINDERIA', 'RATED 4.8 · 0.4 KM'],
    ['SURF', 'URBIZTONDO RENTALS', 'RATED 4.9 · 1.2 KM'],
    ['COFFEE', 'GRIND + GROUNDS', 'RATED 4.7 · 0.8 KM'],
    ['NIGHT', 'SAN JUAN NIGHT MARKET', 'RATED 4.6 · 6 KM'],
  ];
  const cy0 = barH + 286, cw2 = 306, chh = 158;
  cards.forEach((cd, i) => {
    const x = 24 + (i % 2) * (cw2 + 16), y = cy0 + Math.floor(i / 2) * (chh + 16);
    g.fillStyle = '#101010'; g.fillRect(x, y, cw2, chh);
    g.strokeStyle = '#222'; g.strokeRect(x, y, cw2, chh);
    g.fillStyle = '#0c0c0c'; g.fillRect(x, y, cw2, 84);
    g.strokeStyle = 'rgba(255,255,255,.05)';
    for (let k = -84; k < cw2; k += 14) { g.beginPath(); g.moveTo(x + k, y + 84); g.lineTo(x + k + 84, y); g.stroke(); }
    g.fillStyle = '#FF5400'; g.fillRect(x + 10, y + 10, cd[0].length * 7 + 16, 18);
    txt(g, cd[0], x + 18, y + 23, '9px "JetBrains Mono", monospace', '#000');
    g.fillStyle = '#FF5400'; g.beginPath(); g.arc(x + cw2 - 22, y + 22, 4, 0, Math.PI * 2); g.fill();
    g.strokeStyle = 'rgba(255,84,0,.4)'; g.beginPath(); g.arc(x + cw2 - 22, y + 22, 8, 0, Math.PI * 2); g.stroke();
    txt(g, cd[1], x + 12, y + 110, '12px "JetBrains Mono", monospace', '#ddd');
    txt(g, cd[2], x + 12, y + 132, '10px "JetBrains Mono", monospace', '#7a7a7a');
    txt(g, 'OPEN · 6AM–8PM', x + 12, y + 148, '9px "JetBrains Mono", monospace', '#4cc38a');
  });
  const mx = 688, my = barH + 286, mw = 288, mh = H - 56 - my;
  g.fillStyle = '#0d0d0d'; g.fillRect(mx, my, mw, mh);
  g.strokeStyle = '#1f1f1f'; g.strokeRect(mx, my, mw, mh);
  txt(g, 'LIVE MAP', mx + 14, my + 24, '10px "JetBrains Mono", monospace', '#FF7A33');
  txt(g, '41 SHOPS · 6 TOWNS', mx + 14, my + 40, '9px "JetBrains Mono", monospace', '#666');
  g.strokeStyle = 'rgba(255,255,255,.05)';
  for (let k = 0; k < mw; k += 24) { g.beginPath(); g.moveTo(mx + k, my + 52); g.lineTo(mx + k, my + mh - 12); g.stroke(); }
  for (let k = 52; k < mh; k += 24) { g.beginPath(); g.moveTo(mx, my + k); g.lineTo(mx + mw, my + k); g.stroke(); }
  g.strokeStyle = '#1e1e1e'; g.lineWidth = 3;
  g.beginPath(); g.moveTo(mx + 20, my + mh - 40); g.lineTo(mx + mw - 30, my + 70); g.stroke();
  g.beginPath(); g.moveTo(mx + 40, my + 60); g.lineTo(mx + mw - 50, my + mh - 30); g.stroke();
  g.lineWidth = 1;
  const pins = [[mx + 60, my + 120], [mx + 150, my + 95], [mx + 210, my + 180], [mx + 110, my + 220], [mx + 240, my + 120]];
  g.setLineDash([4, 4]); g.strokeStyle = 'rgba(255,84,0,.4)';
  g.beginPath(); g.moveTo(pins[0][0], pins[0][1]);
  pins.slice(1, 4).forEach(pt2 => g.lineTo(pt2[0], pt2[1]));
  g.stroke(); g.setLineDash([]);
  pins.forEach((pt2, i) => {
    g.fillStyle = i === 1 ? '#FF5400' : '#c8c8c8';
    g.beginPath(); g.arc(pt2[0], pt2[1], i === 1 ? 5 : 3.5, 0, Math.PI * 2); g.fill();
    if (i === 1) { g.strokeStyle = 'rgba(255,84,0,.5)'; g.beginPath(); g.arc(pt2[0], pt2[1], 10, 0, Math.PI * 2); g.stroke(); }
  });
  g.strokeStyle = '#333'; g.strokeRect(mx + mw - 46, my + mh - 58, 22, 22); g.strokeRect(mx + mw - 46, my + mh - 32, 22, 22);
  txt(g, '+', mx + mw - 40, my + mh - 42, '12px "JetBrains Mono", monospace', '#c8c8c8');
  txt(g, '-', mx + mw - 40, my + mh - 16, '12px "JetBrains Mono", monospace', '#c8c8c8');
  shotFooter(g, W, H, '41 LISTINGS · UPDATED DAILY', 'VANILLA JS · LEAFLET');
  shotFinish(g, W, H, barH);
  return c.toDataURL('image/jpeg', .85);
}

/* — 4: phone app mockup — */
function shotPhone(p) {
  const W = 1000, H = 760, c = makeCanvas(W, H), g = c.getContext('2d');
  const barH = shotChrome(g, W, H, 'QUIZFORGE — REVIEW APP', 'pwa · offline-first');
  g.fillStyle = 'rgba(255,255,255,.03)';
  for (let y = barH + 2; y < H - 30; y += 28) for (let x = 0; x < W; x += 28) g.fillRect(x, y, 1, 1);
  const px = 350, py = barH + 30, pw = 300, ph = H - barH - 90;
  g.fillStyle = '#0a0a0a'; rrect(g, px, py, pw, ph, 34); g.fill();
  g.strokeStyle = '#2f2f2f'; g.lineWidth = 2; rrect(g, px, py, pw, ph, 34); g.stroke(); g.lineWidth = 1;
  g.fillStyle = '#000'; rrect(g, px + pw / 2 - 55, py + 8, 110, 20, 10); g.fill();
  txt(g, '9:41', px + 22, py + 40, '11px "JetBrains Mono", monospace', '#c8c8c8');
  for (let k = 0; k < 4; k++) { g.fillStyle = k < 3 ? '#c8c8c8' : '#444'; g.fillRect(px + pw - 88 + k * 8, py + 30, 5, 4 + k * 2); }
  g.strokeStyle = '#c8c8c8'; g.strokeRect(px + pw - 46, py + 28, 26, 12);
  g.fillStyle = '#FF5400'; g.fillRect(px + pw - 44, py + 30, 18, 8);
  txt(g, 'QUIZFORGE', px + 22, py + 84, '26px "Bebas Neue", Arial', '#f0f0f0');
  g.strokeStyle = '#FF7A33'; g.strokeRect(px + pw - 150, py + 68, 128, 22);
  txt(g, 'IT-311 · WEBTECH', px + pw - 142, py + 83, '9px "JetBrains Mono", monospace', '#FF7A33');
  txt(g, 'QUESTION 14 / 50', px + 22, py + 116, '9px "JetBrains Mono", monospace', '#6a6a6a');
  g.fillStyle = '#1a1a1a'; g.fillRect(px + 22, py + 124, pw - 44, 6);
  g.fillStyle = '#FF5400'; g.fillRect(px + 22, py + 124, (pw - 44) * 0.28, 6);
  txt(g, 'Which protocol secures HTTP', px + 22, py + 164, '13px "JetBrains Mono", monospace', '#d8d8d8');
  txt(g, 'traffic through TLS on 443?', px + 22, py + 184, '13px "JetBrains Mono", monospace', '#d8d8d8');
  ['A · FTP', 'B · HTTPS', 'C · SMTP', 'D · TELNET'].forEach((o, i) => {
    const y = py + 210 + i * 64, selO = i === 1;
    if (selO) { g.fillStyle = '#FF5400'; rrect(g, px + 22, y, pw - 44, 50, 8); g.fill(); }
    else { g.strokeStyle = '#2a2a2a'; rrect(g, px + 22, y, pw - 44, 50, 8); g.stroke(); }
    txt(g, o, px + 40, y + 31, '13px "JetBrains Mono", monospace', selO ? '#000' : '#b5b5b5');
    if (selO) {
      g.strokeStyle = '#000'; g.lineWidth = 2.5;
      g.beginPath(); g.moveTo(px + pw - 64, y + 22); g.lineTo(px + pw - 56, y + 30); g.lineTo(px + pw - 40, y + 14); g.stroke();
      g.lineWidth = 1;
    }
  });
  txt(g, 'STREAK', px + 22, py + ph - 40, '9px "JetBrains Mono", monospace', '#6a6a6a');
  txt(g, '12', px + 22, py + ph - 14, '32px "Bebas Neue", Arial', '#FF5400');
  txt(g, 'DAYS', px + 60, py + ph - 14, '12px "JetBrains Mono", monospace', '#8a8a8a');
  txt(g, 'SHARDS 340', px + pw - 26, py + ph - 14, '12px "JetBrains Mono", monospace', '#c8c8c8', 'right');
  function note(x, y, leaderX, leaderY, text) {
    g.strokeStyle = 'rgba(255,122,51,.5)'; g.setLineDash([4, 4]);
    g.beginPath(); g.moveTo(leaderX, leaderY); g.lineTo(x, y + 4); g.stroke(); g.setLineDash([]);
    g.fillStyle = '#FF5400'; g.beginPath(); g.arc(leaderX, leaderY, 3, 0, Math.PI * 2); g.fill();
    txt(g, text, x + 8, y + 4, '11px "JetBrains Mono", monospace', '#9a9a9a');
  }
  note(680, 180, px + pw, py + 120, 'WORKS OFFLINE — PWA');
  note(680, 320, px + pw, py + 300, 'SPACED REPETITION ENGINE');
  note(680, 470, px + pw, py + 430, 'SAVES TO LOCALSTORAGE');
  note(60, 620, px, py + ph - 30, 'NO SERVER · NO ACCOUNT');
  shotFooter(g, W, H, 'REVIEW MODE: FOCUSED', 'BUILD: PWA');
  shotFinish(g, W, H, barH);
  return c.toDataURL('image/jpeg', .85);
}

/* — 5: kanban board — */
function shotKanban(p) {
  const W = 1000, H = 760, c = makeCanvas(W, H), g = c.getContext('2d');
  const barH = shotChrome(g, W, H, 'TASKFLOW — SPRINT 12', 'autosaved · just now');
  const cols = [
    { t: 'TODO', n: 5, x: 24, cards: [['FE', 'fix login redirect', '2d'], ['BUG', 'drag ghost flicker', '1d'], ['UI', 'empty-state art', '4d'], ['API', 'task pagination', '3d'], ['DOC', 'readme v2', '—']] },
    { t: 'IN PROGRESS', n: 2, x: 348, cards: [['FE', 'offline layer', '1d'], ['UI', 'cmd+k shortcuts', '2d']] },
    { t: 'DONE', n: 7, x: 672, cards: [['FE', 'board routing', 'ok'], ['UI', 'theme tokens', 'ok'], ['FE', 'drag engine', 'ok'], ['API', 'task crud', 'ok']] },
  ];
  const cw = 304;
  const tagCol = { FE: 'rgba(255,84,0,.16)', BUG: 'rgba(229,72,77,.16)', UI: 'rgba(76,195,138,.13)', API: 'rgba(212,165,58,.13)', DOC: 'rgba(200,200,200,.08)' };
  cols.forEach(col => {
    g.fillStyle = 'rgba(255,255,255,.02)'; rrect(g, col.x, barH + 22, cw, H - barH - 84, 8); g.fill();
    txt(g, col.t, col.x + 16, barH + 48, '12px "JetBrains Mono", monospace', '#9a9a9a');
    const bw = String(col.n).length > 1 ? 30 : 22;
    g.fillStyle = col.t === 'IN PROGRESS' ? '#FF5400' : '#262626';
    g.fillRect(col.x + cw - 16 - bw, barH + 34, bw, 20);
    txt(g, String(col.n), col.x + cw - 16 - bw + 7, barH + 48, '11px "JetBrains Mono", monospace', col.t === 'IN PROGRESS' ? '#000' : '#c8c8c8');
    let y = barH + 70;
    col.cards.forEach(cd => {
      const ch = 64;
      g.fillStyle = '#151515'; rrect(g, col.x + 12, y, cw - 24, ch, 6); g.fill();
      g.strokeStyle = '#232323'; rrect(g, col.x + 12, y, cw - 24, ch, 6); g.stroke();
      g.fillStyle = tagCol[cd[0]] || 'rgba(255,255,255,.06)';
      g.fillRect(col.x + 24, y + 10, 34, 16);
      txt(g, cd[0], col.x + 29, y + 22, '9px "JetBrains Mono", monospace', '#c8c8c8');
      txt(g, cd[1], col.x + 66, y + 23, '12px "JetBrains Mono", monospace', '#dcdcdc');
      g.fillStyle = '#3a3a3a'; g.beginPath(); g.arc(col.x + 32, y + ch - 16, 7, 0, Math.PI * 2); g.fill();
      g.fillStyle = '#FF5400'; g.fillRect(col.x + 30, y + ch - 18, 4, 4);
      txt(g, cd[2], col.x + cw - 34, y + ch - 12, '10px "JetBrains Mono", monospace', '#7a7a7a', 'right');
      y += ch + 14;
    });
    if (col.t === 'DONE') txt(g, '+ 3 MORE…', col.x + 24, y + 14, '10px "JetBrains Mono", monospace', '#555');
  });
  g.fillStyle = '#FF5400'; g.fillRect(348 + 12, barH + 70, 3, 64);
  shotFooter(g, W, H, 'SPRINT 12 · DAY 8 OF 14', 'REACT · DND-KIT');
  shotFinish(g, W, H, barH);
  return c.toDataURL('image/jpeg', .85);
}

/* — 6: game screen — */
function shotGame(p) {
  const W = 1000, H = 760, c = makeCanvas(W, H), g = c.getContext('2d');
  const barH = shotChrome(g, W, H, 'PIXEL DASH — RUN.JS', 'canvas · 60fps · web audio');
  const gx = 20, gy = barH + 14, gw = W - 40, gh = H - 30 - (barH + 14) - 14;
  g.fillStyle = '#060608'; g.fillRect(gx, gy, gw, gh);
  for (let i = 0; i < 70; i++) {
    g.fillStyle = 'rgba(255,255,255,' + (0.1 + Math.random() * 0.35) + ')';
    g.fillRect(gx + Math.random() * gw, gy + Math.random() * gh * 0.7, 2, 2);
  }
  g.strokeStyle = 'rgba(200,200,200,.5)'; g.lineWidth = 2;
  g.beginPath(); g.arc(gx + gw - 140, gy + 80, 34, 0, Math.PI * 2); g.stroke();
  g.fillStyle = '#060608'; g.beginPath(); g.arc(gx + gw - 128, gy + 70, 30, 0, Math.PI * 2); g.fill();
  g.lineWidth = 1;
  txt(g, 'HI 03400', gx + 18, gy + 30, '16px "JetBrains Mono", monospace', '#8a8a8a');
  txt(g, 'SCORE 03412', gx + gw - 18, gy + 30, '16px "JetBrains Mono", monospace', '#FF5400', 'right');
  const groundY = gy + gh - 64;
  g.strokeStyle = '#2f2f2f'; g.lineWidth = 2;
  g.beginPath(); g.moveTo(gx, groundY); g.lineTo(gx + gw, groundY); g.stroke(); g.lineWidth = 1;
  for (let i = 0; i < 60; i++) {
    g.fillStyle = 'rgba(255,255,255,' + (0.04 + Math.random() * 0.06) + ')';
    g.fillRect(gx + Math.random() * gw, groundY + 6 + Math.random() * 26, 4 + Math.random() * 10, 2);
  }
  const rx2 = gx + 150, ry = groundY - 64;
  g.fillStyle = '#FF5400'; g.fillRect(rx2, ry, 26, 30);
  g.fillStyle = '#B33A00'; g.fillRect(rx2 + 16, ry, 10, 30);
  g.fillStyle = '#fff'; g.fillRect(rx2 + 18, ry + 6, 5, 5);
  g.fillStyle = '#FF5400'; g.fillRect(rx2 + 4, ry + 30, 7, 14);
  g.fillRect(rx2 + 15, ry + 30, 7, 9);
  g.fillStyle = '#FF7A33'; g.fillRect(rx2 - 8, ry + 6, 8, 8);
  g.fillStyle = 'rgba(200,200,200,.25)';
  g.fillRect(rx2 - 58, ry + 4, 26, 2); g.fillRect(rx2 - 70, ry + 14, 30, 2); g.fillRect(rx2 - 54, ry + 24, 22, 2);
  function cactus(x) {
    g.fillStyle = '#232323'; g.fillRect(x, groundY - 44, 14, 44);
    g.fillStyle = '#2e2e2e'; g.fillRect(x + 2, groundY - 44, 4, 44);
    g.fillStyle = '#232323';
    g.fillRect(x - 8, groundY - 30, 8, 4); g.fillRect(x - 8, groundY - 40, 4, 14);
    g.fillRect(x + 14, groundY - 24, 8, 4); g.fillRect(x + 20, groundY - 34, 4, 14);
  }
  cactus(gx + 620); cactus(gx + 780); cactus(gx + 880);
  g.strokeStyle = 'rgba(255,84,0,.6)'; g.strokeRect(gx + gw - 96, gy + gh - 40, 78, 24);
  txt(g, '60 FPS', gx + gw - 80, gy + gh - 23, '11px "JetBrains Mono", monospace', '#FF7A33');
  shotFooter(g, W, H, 'RUN 118 — PERSONAL BEST', 'CANVAS 2D · RAF');
  shotFinish(g, W, H, barH);
  return c.toDataURL('image/jpeg', .85);
}

/* — 7: conversational AI assistant mockup (Auralis AI) — */
function shotAuralis(p) {
  const W = 1000, H = 760, c = makeCanvas(W, H), g = c.getContext('2d');
  const barH = shotChrome(g, W, H, 'AURALIS AI — CONVERSATIONAL LLM WORKSPACE', 'auralis.ai · gpt-oss-120b');
  
  // Background canvas (warm cream/sand aesthetic)
  g.fillStyle = '#F5EFEB';
  g.fillRect(0, barH + 2, W, H - barH - 32);

  // Left Sidebar
  const sbW = 220;
  g.fillStyle = '#EBE3DA';
  g.fillRect(0, barH + 2, sbW, H - barH - 32);
  g.fillStyle = '#DDD3C7';
  g.fillRect(sbW, barH + 2, 1, H - barH - 32);

  // Logo & App Name
  g.fillStyle = '#8C5835';
  rrect(g, 16, barH + 18, 26, 26, 6); g.fill();
  g.fillStyle = '#FFF';
  g.beginPath();
  g.arc(29, barH + 31, 3.5, 0, Math.PI * 2);
  g.fill();
  txt(g, 'Auralis', 48, barH + 36, '700 16px "Archivo", Arial', '#2A231E');

  // + New chat button
  g.fillStyle = '#8C5835';
  rrect(g, 16, barH + 58, sbW - 32, 36, 8); g.fill();
  txt(g, '+  New chat', 60, barH + 81, '600 13px "JetBrains Mono", monospace', '#FFFFFF');

  // Search input
  g.fillStyle = '#E2D9CE';
  rrect(g, 16, barH + 104, sbW - 32, 32, 6); g.fill();
  txt(g, '🔍  Search chats...', 26, barH + 124, '11px "JetBrains Mono", monospace', '#7C7166');

  // Chats section
  txt(g, 'CHATS', 18, barH + 158, '600 10px "JetBrains Mono", monospace', '#8C8074');
  
  // Filter pills
  g.fillStyle = '#FFFFFF';
  rrect(g, 16, barH + 168, 48, 24, 6); g.fill();
  txt(g, 'All', 30, barH + 184, '600 10px "JetBrains Mono", monospace', '#2A231E');

  g.strokeStyle = '#D5CBC0';
  rrect(g, 68, barH + 168, 64, 24, 6); g.stroke();
  txt(g, '☆ Pinned', 74, barH + 184, '10px "JetBrains Mono", monospace', '#7C7166');

  rrect(g, 136, barH + 168, 68, 24, 6); g.stroke();
  txt(g, 'Archived', 142, barH + 184, '10px "JetBrains Mono", monospace', '#7C7166');

  // Recent chat items
  const recentChats = ['Draft a status email', 'Explain indexes (SQL)', 'Brainstorm app names', 'REST vs GraphQL'];
  recentChats.forEach((chat, idx) => {
    const cy = barH + 210 + idx * 34;
    if (idx === 0) {
      g.fillStyle = 'rgba(140,88,53,0.12)';
      rrect(g, 16, cy, sbW - 32, 28, 6); g.fill();
    }
    txt(g, '💬 ' + chat, 24, cy + 18, '11px "JetBrains Mono", monospace', idx === 0 ? '#8C5835' : '#5C5248');
  });

  // User profile bottom
  g.fillStyle = '#E2D9CE';
  rrect(g, 16, H - 74, sbW - 32, 36, 6); g.fill();
  g.fillStyle = '#C4A482';
  g.beginPath(); g.arc(34, H - 56, 12, 0, Math.PI * 2); g.fill();
  txt(g, 'AD', 26, H - 52, '700 9px "JetBrains Mono", monospace', '#FFFFFF');
  txt(g, 'Administrator', 52, H - 60, '600 11px "Archivo", Arial', '#2A231E');
  txt(g, 'Enterprise', 52, H - 48, '9px "JetBrains Mono", monospace', '#8C8074');

  // Top Bar in Main Content
  const mainX = sbW + 20;
  txt(g, 'New conversation', mainX + 10, barH + 34, '600 15px "Archivo", Arial', '#2A231E');

  // Model selector pill
  g.strokeStyle = '#D5CBC0';
  g.fillStyle = '#FAF7F4';
  rrect(g, W - 180, barH + 16, 160, 30, 15); g.fill(); g.stroke();
  txt(g, '✨ GPT-OSS 120B  ▾', W - 168, barH + 35, '600 11px "JetBrains Mono", monospace', '#8C5835');

  // Center Hero Content
  const heroY = barH + 130;
  const centerX = sbW + (W - sbW) / 2;

  // Center Icon Badge
  g.fillStyle = '#8C5835';
  rrect(g, centerX - 26, heroY, 52, 52, 16); g.fill();
  g.fillStyle = '#FFF';
  g.beginPath();
  g.arc(centerX, heroY + 26, 8, 0, Math.PI * 2);
  g.fill();

  // "How can I help you today?"
  g.textAlign = 'center';
  txt(g, 'How can I help you today?', centerX, heroY + 96, '600 32px Georgia, serif', '#2A231E');
  txt(g, 'Ask anything — or pick a starting point. Files and images are supported in this workspace.', centerX, heroY + 124, '12px "JetBrains Mono", monospace', '#7C7166');

  // Suggestion Chips
  const chips = [
    '✉️  Draft a status email',
    '🗄️  Explain indexes (SQL)',
    '💡  Brainstorm app names',
    '⚡  REST vs GraphQL'
  ];
  const chipW = 180, chipH = 34, gapX = 14, gapY = 12;
  const chipStartX = centerX - chipW - gapX / 2;
  const chipStartY = heroY + 152;

  chips.forEach((chText, idx) => {
    const cx = idx % 2 === 0 ? chipStartX : chipStartX + chipW + gapX;
    const cy = chipStartY + Math.floor(idx / 2) * (chipH + gapY);
    g.fillStyle = '#FFFFFF';
    g.strokeStyle = '#DCD3C7';
    rrect(g, cx, cy, chipW, chipH, 17); g.fill(); g.stroke();
    g.textAlign = 'center';
    txt(g, chText, cx + chipW / 2, cy + 21, '500 11px "JetBrains Mono", monospace', '#3A322C');
  });

  // Bottom Input Bar
  const inputW = Math.min(580, W - sbW - 80);
  const inputX = centerX - inputW / 2;
  const inputY = H - 120;

  g.fillStyle = '#FFFFFF';
  g.strokeStyle = '#D9D0C4';
  g.shadowColor = 'rgba(0,0,0,0.06)';
  g.shadowBlur = 14;
  g.shadowOffsetY = 4;
  rrect(g, inputX, inputY, inputW, 50, 25); g.fill(); g.stroke();
  g.shadowColor = 'transparent';

  g.textAlign = 'left';
  txt(g, '📎', inputX + 16, inputY + 31, '14px Arial', '#8C8074');
  txt(g, 'Message Auralis...', inputX + 44, inputY + 31, '13px "JetBrains Mono", monospace', '#998D80');

  // Send button
  g.fillStyle = '#8C5835';
  g.beginPath(); g.arc(inputX + inputW - 24, inputY + 25, 16, 0, Math.PI * 2); g.fill();
  g.fillStyle = '#FFFFFF';
  txt(g, '➔', inputX + inputW - 30, inputY + 30, '700 12px Arial', '#FFFFFF');

  // Disclaimer
  g.textAlign = 'center';
  txt(g, 'Auralis can make mistakes. Check important info. Enter sends · Shift+Enter new line', centerX, inputY + 68, '10px "JetBrains Mono", monospace', '#998D80');
  g.textAlign = 'left';

  shotFooter(g, W, H, 'AI WORKSPACE: MULTI-MODEL ROUTING', 'LARAVEL · VANILLA PHP · REST API · MYSQL');
  shotFinish(g, W, H, barH);
  return c.toDataURL('image/jpeg', .85);
}

/* ---------- avatars & portrait ---------- */
function makeAvatar(ii, idx) {
  const S = 160, c = makeCanvas(S, S), g = c.getContext('2d');
  g.fillStyle = '#0f0f0f'; g.fillRect(0, 0, S, S);
  const mode = idx % 4;
  if (mode === 0) {
    g.font = '11px "JetBrains Mono", monospace';
    for (let i = 0; i < 34; i++) { g.fillStyle = 'rgba(190,190,190,' + (0.05 + Math.random() * 0.09) + ')'; g.fillText(rc(), Math.random() * S, Math.random() * S); }
  } else if (mode === 1) {
    g.strokeStyle = 'rgba(190,190,190,.10)';
    for (let k = 0; k <= S; k += 16) { g.beginPath(); g.moveTo(k, 0); g.lineTo(k, S); g.stroke(); g.beginPath(); g.moveTo(0, k); g.lineTo(S, k); g.stroke(); }
  } else if (mode === 2) {
    g.strokeStyle = 'rgba(190,190,190,.10)';
    for (let k = -S; k < S; k += 18) { g.beginPath(); g.moveTo(k, 0); g.lineTo(k + S, S); g.stroke(); }
  } else {
    g.font = '11px "JetBrains Mono", monospace';
    for (let i = 0; i < 40; i++) { g.fillStyle = 'rgba(190,190,190,' + (0.05 + Math.random() * 0.10) + ')'; g.fillText(Math.random() < .5 ? '0' : '1', Math.random() * S, Math.random() * S); }
  }
  g.textAlign = 'center'; g.textBaseline = 'middle';
  g.font = '700 58px Oswald, Arial'; g.fillStyle = '#f2f2f2'; g.fillText(ii, S / 2, S / 2 - 6);
  g.fillStyle = '#FF5400'; g.fillRect(S / 2 - 15, S / 2 + 30, 30, 4);
  g.textAlign = 'left'; g.textBaseline = 'alphabetic';
  return c.toDataURL('image/png');
}

const SHOT_BUILDERS = { dashboard: shotDashboard, queue: shotQueue, website: shotWebsite, phone: shotPhone, kanban: shotKanban, game: shotGame, auralis: shotAuralis };
let imagesDone = false;
function generateImages() {
  if (imagesDone) return;
  imagesDone = true;
  PROJECTS.forEach(p => {
    if (!p.shot) p.shot = (SHOT_BUILDERS[p.ui] || shotDashboard)(p);
  });
  document.querySelectorAll('img[data-ii]').forEach((im, idx) => { im.src = makeAvatar(im.dataset.ii, idx); });
  vpImg.src = PROJECTS[0].shot;
}

/* ---------- boot scenes + images once fonts are ready ---------- */
(function () {
  let ran = false;
  const run = () => { if (ran) return; ran = true; setupScenes(); generateImages(); };
  if (document.fonts && document.fonts.load) {
    Promise.all([
      document.fonts.load('400 14px "JetBrains Mono"'),
      document.fonts.load('700 20px Oswald'),
      document.fonts.load('400 40px "Bebas Neue"'),
    ]).then(() => document.fonts.ready).then(run).catch(run);
    setTimeout(run, 2400);
  } else run();
})();

/* ---------- Toast ---------- */
const toast = document.getElementById('toast');
let toastT;
function showToast(title, msg) {
  document.getElementById('toastTitle').textContent = title;
  document.getElementById('toastMsg').textContent = msg;
  toast.classList.add('visible');
  clearTimeout(toastT);
  toastT = setTimeout(() => toast.classList.remove('visible'), 3600);
}

/* ---------- Preloader ---------- */
(function () {
  const pl = document.getElementById('preloader');
  const num = document.getElementById('plNum');
  const bar = document.getElementById('plBar');
  const dur = reduceMotion ? 0 : 1100;
  const t0 = performance.now();
  function finish() {
    pl.classList.add('done');
    document.body.classList.add('loaded');
    setTimeout(() => { pl.style.display = 'none'; }, 900);
    setTimeout(initReveals, 300);
  }
  (function frame(t) {
    const p = dur ? Math.min((t - t0) / dur, 1) : 1;
    const e = 1 - Math.pow(1 - p, 2);
    num.textContent = String(Math.round(e * 100)).padStart(3, '0');
    bar.style.width = (e * 100) + '%';
    if (p < 1) requestAnimationFrame(frame);
    else setTimeout(finish, 150);
  })(performance.now());
})();

/* ---------- Scroll reveals ---------- */
function initReveals() {
  const io = new IntersectionObserver(entries => {
    entries.forEach(e => {
      if (e.isIntersecting) {
        e.target.classList.add('in-view');
        if (e.target.classList.contains('reveal-stagger')) {
          setTimeout(() => e.target.classList.add('stagger-done'), 1400);
        }
        io.unobserve(e.target);
      }
    });
  }, { threshold: 0.12, rootMargin: '0px 0px -8% 0px' });
  document.querySelectorAll('.reveal, .reveal-stagger').forEach(el => io.observe(el));
}

/* ---------- Animated counters ---------- */
(function () {
  const io = new IntersectionObserver(entries => {
    entries.forEach(en => {
      if (!en.isIntersecting) return;
      io.unobserve(en.target);
      const el = en.target;
      const target = +el.dataset.count;
      const padLen = +(el.dataset.pad || 0);
      const suffix = el.dataset.suffix || '';
      const dur = 1600, t0 = performance.now();
      (function fr(t) {
        let p = Math.min((t - t0) / dur, 1);
        p = 1 - Math.pow(1 - p, 3);
        el.textContent = String(Math.round(target * p)).padStart(padLen, '0') + suffix;
        if (p < 1) requestAnimationFrame(fr);
      })(t0);
    });
  }, { threshold: 0.5 });
  document.querySelectorAll('.number-display[data-count]').forEach(cn => io.observe(cn));
})();

/* ---------- Hero showreel (crossfades + drives active scene) ---------- */
(function () {
  const prog = document.getElementById('reelProgress');
  const chap = document.getElementById('chapterNum');
  const lab = document.getElementById('reelLabel');
  const DUR = 6000;
  let fi = 0, elapsed = 0, last = null;
  function activate(i) {
    frames[fi].classList.remove('active');
    fi = i;
    frames[fi].classList.add('active');
    chap.textContent = pad2(fi + 1);
    if (lab) lab.textContent = 'SHOWREEL — ' + SCENE_NAMES[fi];
    elapsed = 0;
    prog.style.width = '0%';
    if (SCENES[fi].wake) SCENES[fi].wake();
  }
  (function loop(t) {
    if (last !== null) {
      const dt = Math.min(t - last, 50);
      elapsed += dt;
      prog.style.width = Math.min(elapsed / DUR * 100, 100) + '%';
      if (elapsed >= DUR) activate((fi + 1) % frames.length);
      if (sceneReady && !reduceMotion && scrollY < innerHeight * 1.1 && !document.hidden) {
        SCENES[fi].draw(ctxs[fi], t / 1000, dt / 1000);
      }
    }
    last = t;
    requestAnimationFrame(loop);
  })(performance.now());
})();



/* ---------- Live Philippine clock ---------- */
(function () {
  const els = document.querySelectorAll('.js-clock');
  const fmt = new Intl.DateTimeFormat('en-GB', {
    hour: '2-digit', minute: '2-digit', second: '2-digit',
    hour12: false, timeZone: 'Asia/Manila'
  });
  function tick() { const s = fmt.format(new Date()); els.forEach(el => el.textContent = s); }
  tick();
  setInterval(tick, 1000);
})();

/* ---------- Floating work preview ---------- */
let mx = innerWidth / 2, my = innerHeight / 2;
let pvX = mx, pvY = my, pvRot = 0;
const pvT = { x: mx, y: my, on: false };

if (finePointer && preview) {
  document.addEventListener('mousemove', e => {
    mx = e.clientX; my = e.clientY;
    if (pvT.on) {
      pvT.x = Math.max(215, Math.min(innerWidth - 215, mx));
      pvT.y = my;
    }
  });
  (function raf() {
    if (pvT.on || Math.abs(pvX - pvT.x) > 0.5 || Math.abs(pvY - pvT.y) > 0.5) {
      pvX += (pvT.x - pvX) * 0.12;
      pvY += (pvT.y - pvY) * 0.12;
      const targetRot = Math.max(-9, Math.min(9, (pvT.x - pvX) * 0.08));
      pvRot += (targetRot - pvRot) * 0.1;
      preview.style.transform = 'translate3d(' + pvX + 'px, ' + (pvY - 115) + 'px, 0) translate(-50%, -50%) rotate(' + pvRot + 'deg) scale(' + (pvT.on ? 1 : 0.88) + ')';
    }
    requestAnimationFrame(raf);
  })();
}

function hidePreview() { if (preview) preview.classList.remove('show'); pvT.on = false; }

/* ---------- Work rows ---------- */
const rows = [...document.querySelectorAll('.work-row')];

rows.forEach(row => {
  const i = +row.dataset.i;
  if (finePointer) {
    row.addEventListener('mouseenter', () => {
      const p = PROJECTS[i];
      vpImg.src = p.shot || FALLBACK_IMG;
      vpImg.alt = p.title + ' preview';
      vpTag.textContent = p.title + ' — ' + p.year;
      pvX = mx; pvY = my; pvT.x = mx; pvT.y = my; pvT.on = true;
      preview.classList.add('show');
    });
    row.addEventListener('mouseleave', hidePreview);
  }
  row.addEventListener('click', () => openModal(i));
  row.addEventListener('keydown', e => {
    if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); openModal(i); }
  });
});

/* ---------- Filters ---------- */
document.getElementById('filterBar').addEventListener('click', e => {
  const btn = e.target.closest('.pill');
  if (!btn) return;
  document.querySelectorAll('#filterBar .pill').forEach(p2 => p2.classList.remove('active'));
  btn.classList.add('active');
  const f = btn.dataset.filter;
  rows.forEach(row => {
    const show = f === 'all' || row.dataset.cat === f;
    if (show) {
      row.style.display = '';
      requestAnimationFrame(() => requestAnimationFrame(() => row.classList.remove('f-hide')));
    } else {
      row.classList.add('f-hide');
      setTimeout(() => { if (row.classList.contains('f-hide')) row.style.display = 'none'; }, 300);
    }
  });
});

/* ---------- Project modal ---------- */
const modal = document.getElementById('modal');
const modalPanel = document.getElementById('modalPanel');
let cur = 0, lastFocus = null;

function renderModal() {
  const p = PROJECTS[cur];
  document.getElementById('mImg').src = p.shot || FALLBACK_IMG;
  document.getElementById('mImg').alt = p.title;
  document.getElementById('mIndex').textContent = pad2(cur + 1) + ' / ' + pad2(PROJECTS.length);
  document.getElementById('mTitle').textContent = p.title;
  document.getElementById('mCat').textContent = p.cat;
  document.getElementById('mDesc').textContent = p.desc;
  document.getElementById('mClient').textContent = p.client;
  document.getElementById('mYear').textContent = p.year;
  document.getElementById('mRole').textContent = p.role;
  document.getElementById('mStack').textContent = p.stack.join(' · ');
  document.getElementById('mMetrics').innerHTML = p.metrics.map(m =>
    '<div class="border-l border-[var(--border-light)] pl-4">' +
    '<div class="font-display text-3xl leading-none">' + m[0] + '</div>' +
    '<div class="font-mono text-[9px] text-[var(--muted)] tracking-[.18em] uppercase mt-2">' + m[1] + '</div>' +
    '</div>').join('');
}

function openModal(i) {
  cur = i;
  renderModal();
  lastFocus = document.activeElement;
  modal.classList.add('open');
  modal.setAttribute('aria-hidden', 'false');
  document.body.classList.add('modal-open');
  hidePreview();
  modal.querySelector('.modal-close').focus();
}
function closeModal() {
  modal.classList.remove('open');
  modal.setAttribute('aria-hidden', 'true');
  document.body.classList.remove('modal-open');
  if (lastFocus) lastFocus.focus();
}
function stepModal(dir) {
  modalPanel.classList.add('swapping');
  setTimeout(() => {
    cur = (cur + dir + PROJECTS.length) % PROJECTS.length;
    renderModal();
    modalPanel.classList.remove('swapping');
  }, 190);
}

modal.querySelectorAll('[data-close]').forEach(el => el.addEventListener('click', closeModal));
document.getElementById('mPrev').addEventListener('click', () => stepModal(-1));
document.getElementById('mNext').addEventListener('click', () => stepModal(1));
document.addEventListener('keydown', e => {
  if (!modal.classList.contains('open')) return;
  if (e.key === 'Escape') closeModal();
  if (e.key === 'ArrowLeft') stepModal(-1);
  if (e.key === 'ArrowRight') stepModal(1);
});

/* ---------- Accordion ---------- */
document.querySelectorAll('.cap-item').forEach(item => {
  item.querySelector('.cap-head').addEventListener('click', () => {
    const wasOpen = item.classList.contains('open');
    document.querySelectorAll('.cap-item.open').forEach(o => {
      o.classList.remove('open');
      o.querySelector('.cap-head').setAttribute('aria-expanded', 'false');
    });
    if (!wasOpen) {
      item.classList.add('open');
      item.querySelector('.cap-head').setAttribute('aria-expanded', 'true');
    }
  });
});

/* ---------- Flip card (click / tap to toggle) ---------- */
(function () {
  const flipCard = document.getElementById('profileFlip');
  if (flipCard) {
    flipCard.addEventListener('click', e => {
      if (e.target.closest('a')) return;
      flipCard.classList.toggle('flipped');
    });
  }
})();

/* ---------- Testimonials Continuous Infinite Slider ---------- */
(function () {
  const wrap = document.getElementById('carouselWrap');
  if (!wrap) return;
  const track = wrap.querySelector('.t-track');
  const counter = document.getElementById('tCounter');
  if (!track) return;

  wrap.scrollLeft = 0;

  // Collect the 6 original cards
  const allExistingCards = Array.from(track.querySelectorAll('.t-card'));
  const originalCards = allExistingCards.slice(0, 6);
  if (originalCards.length === 0) return;

  let singleCycleWidth = 0;
  let cardStep = 0;
  let offset = 0;
  const speed = 0.85; // Continuous smooth speed (pixels per frame)
  let isPaused = false;
  let isDragging = false;
  let dragStartX = 0;
  let dragLastX = 0;

  function setupTrackClones() {
    wrap.scrollLeft = 0;
    track.innerHTML = '';

    // Append first original set
    originalCards.forEach(c => track.appendChild(c.cloneNode(true)));

    // Calculate card width and step
    const firstCard = track.querySelector('.t-card');
    const cardW = firstCard ? firstCard.offsetWidth : 400;
    const gap = 24; // 1.5rem gap
    cardStep = cardW + gap;
    singleCycleWidth = originalCards.length * cardStep;

    // Determine how many duplicate sets are needed to ensure screen is ALWAYS full even on extreme zoom out
    const viewW = window.innerWidth || document.documentElement.clientWidth || 1920;
    const minSetsNeeded = Math.max(4, Math.ceil((viewW * 2.5) / singleCycleWidth) + 2);

    for (let s = 1; s < minSetsNeeded; s++) {
      originalCards.forEach(c => {
        const clone = c.cloneNode(true);
        clone.setAttribute('aria-hidden', 'true');
        track.appendChild(clone);
      });
    }

    // Refresh avatar images on all cards
    track.querySelectorAll('img[data-ii]').forEach((im, idx) => {
      if (typeof makeAvatar === 'function') {
        im.src = makeAvatar(im.dataset.ii, idx % originalCards.length);
      }
    });
  }

  setupTrackClones();

  function updateCounterDisplay() {
    if (!counter || singleCycleWidth <= 0 || cardStep <= 0) return;
    const normalized = ((-offset) % singleCycleWidth + singleCycleWidth) % singleCycleWidth;
    const activeIdx = Math.floor((normalized + cardStep * 0.45) / cardStep) % originalCards.length;
    counter.textContent = pad2(activeIdx + 1) + ' / ' + pad2(originalCards.length);
  }

  function render() {
    if (!isPaused && !isDragging && singleCycleWidth > 0) {
      offset -= speed;
    }

    // Seamless infinite continuous wrap (zero visual cut or jump)
    if (singleCycleWidth > 0) {
      while (offset <= -singleCycleWidth) {
        offset += singleCycleWidth;
      }
      while (offset > 0) {
        offset -= singleCycleWidth;
      }
    }

    track.style.transform = 'translate3d(' + offset.toFixed(2) + 'px, 0, 0)';
    updateCounterDisplay();

    requestAnimationFrame(render);
  }

  // Hover to pause so reader can inspect any field report
  wrap.addEventListener('mouseenter', () => { isPaused = true; });
  wrap.addEventListener('mouseleave', () => {
    isPaused = false;
    if (isDragging) {
      isDragging = false;
      wrap.classList.remove('dragging');
    }
  });

  // Smooth pointer / touch dragging
  function handleDragStart(e) {
    isDragging = true;
    dragStartX = e.touches ? e.touches[0].clientX : e.clientX;
    dragLastX = dragStartX;
    wrap.classList.add('dragging');
  }

  function handleDragMove(e) {
    if (!isDragging) return;
    const currentX = e.touches ? e.touches[0].clientX : e.clientX;
    const delta = currentX - dragLastX;
    dragLastX = currentX;
    offset += delta;

    if (singleCycleWidth > 0) {
      while (offset <= -singleCycleWidth) offset += singleCycleWidth;
      while (offset > 0) offset -= singleCycleWidth;
    }
  }

  function handleDragEnd() {
    if (isDragging) {
      isDragging = false;
      wrap.classList.remove('dragging');
    }
  }

  wrap.addEventListener('mousedown', handleDragStart);
  window.addEventListener('mousemove', handleDragMove);
  window.addEventListener('mouseup', handleDragEnd);

  wrap.addEventListener('touchstart', handleDragStart, { passive: true });
  window.addEventListener('touchmove', handleDragMove, { passive: true });
  window.addEventListener('touchend', handleDragEnd, { passive: true });

  // Handle window resize or zoom changes seamlessly
  let resizeTimer;
  window.addEventListener('resize', () => {
    clearTimeout(resizeTimer);
    resizeTimer = setTimeout(() => {
      setupTrackClones();
    }, 200);
  });

  requestAnimationFrame(render);
})();



/* ---------- Copy to clipboard ---------- */
function copyText(t) {
  const done = () => showToast('COPIED TO CLIPBOARD', t);
  const fallback = () => {
    const ta = document.createElement('textarea');
    ta.value = t;
    ta.style.position = 'fixed';
    ta.style.opacity = '0';
    document.body.appendChild(ta);
    ta.select();
    try { document.execCommand('copy'); done(); }
    catch (_) { showToast('COPY FAILED', t); }
    ta.remove();
  };
  if (navigator.clipboard && window.isSecureContext) {
    navigator.clipboard.writeText(t).then(done).catch(fallback);
  } else fallback();
}
document.querySelectorAll('[data-copy]').forEach(b =>
  b.addEventListener('click', () => copyText(b.dataset.copy))
);

/* ---------- Contact form ---------- */
document.querySelectorAll('.pill-group').forEach(group => {
  group.querySelectorAll('.pill').forEach(p2 => p2.addEventListener('click', () => {
    group.querySelectorAll('.pill').forEach(x => x.classList.remove('active'));
    p2.classList.add('active');
  }));
});

(function () {
  const form = document.getElementById('contactForm');
  const status = document.getElementById('formStatus');
  const fields = {
    name: document.getElementById('fName'),
    email: document.getElementById('fEmail'),
    msg: document.getElementById('fMsg')
  };
  Object.values(fields).forEach(el =>
    el.addEventListener('input', () => el.classList.remove('input-error'))
  );
  form.addEventListener('submit', e => {
    e.preventDefault();
    status.className = 'form-status';
    const errs = [];
    if (fields.name.value.trim().length < 2) { fields.name.classList.add('input-error'); errs.push('NAME REQUIRED'); }
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(fields.email.value.trim())) { fields.email.classList.add('input-error'); errs.push('VALID EMAIL REQUIRED'); }
    if (fields.msg.value.trim().length < 10) { fields.msg.classList.add('input-error'); errs.push('MESSAGE TOO SHORT — GIVE ME SOMETHING TO BUILD'); }
    if (errs.length) {
      status.textContent = errs[0];
      status.classList.add('error');
      return;
    }
    const first = fields.name.value.trim().split(' ')[0];
    status.textContent = 'Transmission logged — expect a reply within a day.';
    status.classList.add('ok');
    showToast('TRANSMISSION RECEIVED', 'Salamat, ' + first + '! I read everything myself and I actually reply — within 24 hours.');
    form.reset();
    document.querySelectorAll('.pill-group').forEach(g => {
      g.querySelectorAll('.pill').forEach((p2, i) => p2.classList.toggle('active', i === 0));
    });
  });
})();

/* ---------- Print résumé ---------- */
const printResumeBtn = document.getElementById('printResume');
if (printResumeBtn) {
  printResumeBtn.addEventListener('click', () => {
    showToast('RÉSUMÉ MODE', 'Choose "Save as PDF" in the print dialog for a clean one-pager.');
    setTimeout(() => window.print(), 500);
  });
}

/* ---------- Back to top ---------- */
document.getElementById('toTop').addEventListener('click', () => {
  scrollTo({ top: 0, behavior: reduceMotion ? 'auto' : 'smooth' });
});

/* ---------- Theme Switcher (Dark / Light Mode) ---------- */
(function () {
  const themeToggle = document.getElementById('themeToggle');
  const themeSun = document.getElementById('themeSun');
  const themeMoon = document.getElementById('themeMoon');
  
  function applyTheme(theme) {
    if (theme === 'light') {
      document.documentElement.setAttribute('data-theme', 'light');
      if (themeSun) themeSun.classList.remove('hidden');
      if (themeMoon) themeMoon.classList.add('hidden');
    } else {
      document.documentElement.removeAttribute('data-theme');
      if (themeSun) themeSun.classList.add('hidden');
      if (themeMoon) themeMoon.classList.remove('hidden');
    }
    localStorage.setItem('va_theme', theme);
  }

  const savedTheme = localStorage.getItem('va_theme') || 'dark';
  applyTheme(savedTheme);

  if (themeToggle) {
    themeToggle.addEventListener('click', () => {
      const current = document.documentElement.getAttribute('data-theme') === 'light' ? 'light' : 'dark';
      const next = current === 'light' ? 'dark' : 'light';
      applyTheme(next);
      showToast('THEME TOGGLED', next === 'light' ? 'Light mode activated.' : 'Dark mode activated.');
    });
  }
})();


/* ---------- Opportunity Intake Dropdown ---------- */
(function () {
  const btn    = document.getElementById('oppDropdownBtn');
  const menu   = document.getElementById('oppDropdownMenu');
  const label  = document.getElementById('oppDropdownLabel');
  const hidden = document.getElementById('fOppType');
  if (!btn || !menu) return;

  function openMenu() {
    menu.classList.add('open');
    btn.setAttribute('aria-expanded', 'true');
  }

  function closeMenu() {
    menu.classList.remove('open');
    btn.setAttribute('aria-expanded', 'false');
  }

  btn.addEventListener('click', (e) => {
    e.stopPropagation();
    const isOpen = menu.classList.contains('open');
    isOpen ? closeMenu() : openMenu();
  });

  // Close when clicking outside
  document.addEventListener('click', (e) => {
    if (!btn.contains(e.target) && !menu.contains(e.target)) {
      closeMenu();
    }
  });

  // Close on Escape key
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') closeMenu();
  });

  // Handle option selection
  menu.querySelectorAll('.opp-option').forEach(opt => {
    opt.addEventListener('click', () => {
      const value = opt.dataset.value;

      // Update hidden input
      if (hidden) hidden.value = value;

      // Update trigger label
      if (label) {
        label.innerHTML = `
          <span class="w-1.5 h-1.5 rounded-full bg-[var(--accent)]"></span>
          <span>${value}</span>`;
      }

      // Update selected state
      menu.querySelectorAll('.opp-option').forEach(o => {
        o.classList.remove('selected');
        const check = o.querySelector('.check-icon');
        if (check) check.classList.add('hidden');
      });
      opt.classList.add('selected');
      const ck = opt.querySelector('.check-icon');
      if (ck) ck.classList.remove('hidden');

      closeMenu();
    });
  });
})();

// Smooth scrolling for internal anchor links (safe for file:// and http/https protocols)
document.addEventListener('DOMContentLoaded', () => {
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function(e) {
      const targetId = this.getAttribute('href');
      if (targetId && targetId !== '#' && targetId.length > 1) {
        const targetElement = document.querySelector(targetId);
        if (targetElement) {
          e.preventDefault();
          targetElement.scrollIntoView({ behavior: 'smooth' });
          if (window.location.protocol !== 'file:') {
            history.pushState(null, '', targetId);
          }
        }
      }
    });
  });
});

